- src/ui/inputwin.c
- src/ui/inputwin.h
This commit adds a common subset of readline style keybindings, as requested in issue #216 and issue #460, which should satisfy most users used to the Unix command line (or Unix clients like `irssi`). It implements the following new bindings:
Profanity Default | Readline Style Equivalent    | Readline Command
----------------- | ---------------------------- | -------------------
<kbd>Del</kbd>    | <kbd>Ctrl</kbd>+<kbd>D</kbd> | `delete-char`
<kbd>←</kbd>      | <kbd>Ctrl</kbd>+<kbd>B</kbd> | `backward-char`
<kbd>→</kbd>      | <kbd>Ctrl</kbd>+<kbd>F</kdb> | `forward-char`
<kbd>↑</kbd>      | <kbd>Ctrl</kbd>+<kbd>P</kdb> | `previous-history`
<kbd>↓</kbd>      | <kbd>Ctrl</kbd>+<kbd>N</kdb> | `next-history`
<kbd>Home</kbd>   | <kbd>Ctrl</kbd>+<kbd>A</kdb> | `beginning-of-line` …
> Add readline-style keybindings

- src/profanity.c
Basically #472 but installed permanent signal handlers in `_init`.
> Ignore more signals in _init

- src/command/commands.c
- src/config/accounts.c
- tests/test_cmd_rooms.c
* `eval_password` handling code is now in `cmd_connect`, so that the field can be changed without clearing itself.
* `pclose` is called on the `popen`ed `eval_password` command, but this is going to fail if the process never terminates. A solution would be to use `fork` instead of `popen` and manually `kill` the pid.
* `stderr` from the `popen`ed process does not make curses mad anyore.
* Added a sanity check for memory allocation of `account->password`.
* Unrelated, but moved the retrieval/freeing of the default account string to more convenient places.
> General fixes related to eval_password

- src/command/commands.c
the "fix a potential leak" from Will Song is not fully addressing the
issue.. so now the "def" variable should definitely being freed
> fix the fix (memory leak)

- src/command/commands.c
Don't know why I forgot to include this in the previous PR. `cmd` should be freed right after nobody uses it anymore.
> Fix yet another potential leak

- src/command/command.c
This is to address a minor annoyance I had with autocomplete.  When I'm logged into FB all the user names show as people's full names with spaces.  When you autocomplete it adds quote characters around a person's name.  However, if you for instance autocomplete then realize that your /msg "Firstname Lastname" has the right first name but wrong last name and you backspace the lastname then the autocomplete will fail when you hit tab again.  This is because the first quote characterbefore Firstname is being used to match against the autocomplete.
This diff strips out beginning and ending quote characters before doing autocomplete.  I chose to do it at this point in the code because it will only impact the user interaction functions (/msg etc) which is really the only area I know of where it …
> Strip quote chars from name autocomplete

- src/ui/inputwin.c
When using readline's standard `^L` binding, the screen
is completely cleared, including status and title bar.
By binding `^L` to profanity's clear method, status and
title bar are retained.
> Bind ^L to own clear method to retain ui elements

- src/plugins/api.c
- src/plugins/api.h
- src/plugins/c_api.c
- src/plugins/lua_api.c
- src/plugins/profapi.c
- src/plugins/profapi.h
- src/plugins/python_api.c
- src/plugins/ruby_api.c
I added the api_get_current_muc function to use the /browser plugin in a muc : https://github.com/olivierlemoal/profanity-plugins/commit/a6dbc7a9128449b31e8c8b82df6d834151e71c43
Please let me know your thoughts on this.
> Add api_get_current_muc() to plugin api

- src/command/commands.c
So I am by no means familiar with the code base, but browsing through it all the logic for enabling / disabling carbons without being connected seemed to already be there. Also this commit seems to work according to my testing.
> allow enabling / disabling carbons without being connected.

- src/command/commands.c
- src/config/theme.c
Adds the command /winstidy which is a boolean option enabled by default. 
When a window is closed it will perform a window tidy command, removing gaps from the window list.
Re: Issue #551
> Added window auto tidy.

- src/command/command.c
Allows for "quoting" a command--doing nothing but sending the string: SPC/command
As we're used to from for example irc clients. 
Fixes boothj5/profanity#513
> Let's only strip trailing whitespace when parsing command

- src/profanity.c
log_msg() uses prefs, so prefs_close() should be called after log_close(). It makes possible to use logs in other finalisation functions.
> Call prefs_close() after log_close()

- src/event/server_events.c
```
src/event/server_events.c: In function ‘sv_ev_incoming_message’:
src/event/server_events.c:259:41: error: ‘jid’ undeclared (first use in this function)
src/event/server_events.c:259:41: note: each undeclared identifier is reported only once for each function it appears in
src/event/server_events.c:257:16: error: unused variable ‘enc_mode’ [-Werror=unused-variable]
```
Recreate:
```
./configure --disable-otr --enable-pgp
make
```
> PGP: Fixed compilation error when libotr is not supported

- src/xmpp/message.c
- src/xmpp/stanza.c
- src/xmpp/stanza.h
This adds the `no-copy` and `no-store` message processing hints to OTR messages as per [XEP-0334](https://xmpp.org/extensions/xep-0334.html).
While the `no-copy` hint effectively does the same thing as the Carbons `private` hint, some clients choose to respect one but not the other.
The `no-store` hint ensures that OTR messages (which are perfect forward secret and can't be read later) are not stored in archives such as the MAM archive.
> Add no-copy and no-store hints to OTR messages

- install-all.sh
The install-all.sh script doesn't check for an existing installation of the [apt-cyg](https://github.com/transcode-open/apt-cyg) script before downloading and installing it into /usr/local/bin/. As the readme of that script recommends installing it into /bin/ this can lead to redundant installation of multiple, potentially different versions of the script.
This patch adds a check for an existing installation of apt-cyg and extracts the installation method into a function.
> Have the installer on cygwin check for an existing installation of apt-cyg

- src/config/preferences.c
- src/muc.c
- src/ui/buffer.c
In two cleanup/free function the pointer got set to NULL so one can later check whether it got freed or not. However this change didn't have any effect outside of the function.
This dereferences it hopefully correctly.
Please review.
> dereferencing pointers

- src/ui/inputwin.c
Casting the into correct type.
> Get rid of compiler warning concerning NULL pointer

- CHANGELOG
- src/command/command.c
- src/command/commands.c
- src/command/commands.h
Fairly self explanatory. Opens up a file descriptor to the desired file (fails and prints the corresponding message) and writes the bare jid and name as CSV entries.
> Implement feature request in #585 (export command)

- src/command/command.c
Noticed a spelling mistake when I was looking up the help text for one of the commands. Went to fix it and noticed a few other ones.
> Fix spelling and grammatical mistakes in command help text

- install-all.sh
So libotr released a patch (libotr 4.1.1) for a interger overflow vulnerability. [0] I was surprised to find profanity was still using a vulnerable version of libotr, turns out the reason libotr version 3.x is forced in the Fedora install. 
This patch fixes that. Tested on Fedora 23 x86_64. I checked the dependencies for other distros, they do not appear to need to be changed. Not sure about cygwin.
[0] https://lists.cypherpunks.ca/pipermail/otr-users/2016-March/002581.html
> libotr upgrade on Fedora

- configure.ac
Profanity fails to build with multiple errors on my system with python-3.5:
```
src/plugins/python_plugins.c: In function ‘python_env_init’:
src/plugins/python_plugins.c:65:34: error: passing argument 1 of ‘g_string_new’ from incompatible pointer type [-Werror]
GString *path = g_string_new(Py_GetPath());
src/plugins/python_plugins.c: In function ‘python_pre_chat_message_display_hook’:
src/plugins/python_plugins.c:245:17: error: implicit declaration of function ‘PyString_AsString’ [-Werror=implicit-function-declaration]
char *result_str = strdup(PyString_AsString(PyUnicode_AsUTF8String(result)));
(many similar errors)
```
This can confuse a user who wants to try Profanity and just build it with `configure && make`.
This patch is just possible quick workaround for the problem.
> Disable python-plugins by default

- src/event/server_events.c
- src/event/server_events.h
- src/muc.c
- src/ui/mucwin.c
- src/xmpp/bookmark.c
- src/xmpp/capabilities.c
- src/xmpp/form.c
- src/xmpp/iq.c
- src/xmpp/message.c
- src/xmpp/presence.c
- src/xmpp/stanza.c
- src/xmpp/stanza.h
- src/xmpp/xmpp.h
In most get-like funcitons libstrophe returns pointer to a string
that resides in an internal structure (e.g. xmpp_stanza_t). Hence,
Profanity must not change such strings. Define respective variables
as 'const char*' to reduce a chance of error and conform future
libstrophe's interface.
This patch mostly replaces 'char *' with 'const char*', but also
fixes two memory leaks after stanza_get_reason(). Add comment within
stanza_get_reason() to fix conflict with different allocator types.
> Define stanza's attributes as const char*

- configure.ac
OS X contains libcurl without a pkg-config file and ./configure
reports error. Add AC_CHECK_LIB in order to find libcurl properly.
Also remove manual adding -lncurses and -lcurl to LIBS, because
AC_CHECK_LIB does this job.
> Fix libcurl check in configure.ac for OS X

- src/command/cmd_funcs.c
- src/otr/otrlibv4.c
- src/ui/notifier.c
While packaging the new 0.5.0 upstream release I came across a few spelling mistakes
Hope this helps :-)
> Correct minor spelling errors

- src/command/cmd_defs.c
_cmd_index() returns string allocated by glib.
> Fix memory leak in cmd_init()

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/config/accounts.c
- src/xmpp/connection.c
Add `legacy` tls policy to /account and /connect commands. When this
policy is specified the connection is connected with
XMPP_CONN_LEGACY_SSL flag. Notice, legacy SSL and STARTTLS are not
compatible and user has to know when exactly the new policy should be
used.
To enable it, run one of the next commands:
```
/connect <jid> tls legacy [server <host>]
/account <name> set tls legacy
```
Notice, there is no SRV record for legacy SSL. Therefore, you may need
`server` property to connect successfully. Refer to configuration
provided by your server.
This patch closes #536.
> Legacy SSL support

- src/command/cmd_funcs.c
Small typo, "pytyon" -> "python".
> Fixed a typo in an error message ("This build does not support python plugins")

- src/command/cmd_funcs.c
Fix typo in error messages about plugins
> Update typo in cmd_funcs.c

- src/log.c
With gcc8 we get the following error when stringop-truncation is on:
```
In function ‘_rotate_log_file’,
inlined from ‘log_msg.part.2’ at src/log.c:201:17:
src/log.c:231:5: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
strncpy(log_file_new, log_file, len);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/log.c: In function ‘log_msg.part.2’:
src/log.c:228:18: note: length computed here
size_t len = strlen(log_file);
^~~~~~~~~~~~~~~~
```
Using memcpy instead of strncpy.
> Fix gcc8 error about strncpy

- Makefile.am
- tests/unittests/test_autocomplete.c
- tests/unittests/test_cmd_bookmark.c
- tests/unittests/test_common.c
- tests/unittests/test_plugins_disco.c
- tests/unittests/test_roster_list.c
- tests/unittests/test_server_events.c
- tests/unittests/tools/stub_http_upload.c
- tests/unittests/unittests.c
The flag hides errors. But we want unit tests to be correct in order
to reveal errors in the main code.
The patch removes tests_unittests_unittests_CFLAGS and makes autotools
use AM_CFLAGS instead. Therefore, unit tests are built with flags
derived from configure.ac.
@jubalh Please, take a look.
> tests: remove cflag -w and fix warnings

- src/ui/inputwin.c
Added possibility to close a window with key binding. _(So you're less likely to send someone e.g. „c/los” message)_
> Add prof_win_close

- src/xmpp/iq.c
- src/xmpp/stanza.c
sessionid appears to be optional in command messages.
Handle it correctly.
> Fix optionnal sessionid in xep 0050

- src/plugins/plugins.c
previously TRUE was returned once one unload operation succeeded
> let plugins_unload_all fail if one plugin unload operation fails

- src/plugins/plugins.c
the plugins_unload function always returned true.
Therefore, plugin unloads for nonexisting plugins succeeded.
> Fail plugin unloading if plugin does not exist

- src/config/accounts.c
- src/xmpp/jid.c
- src/xmpp/jid.h
- src/xmpp/session.c
When connecting for the first time or when creating a new account don't
use only 'profanity' as default resource.
Some server don't support having 2 connection with same resource. Using
profanity as default lead to deconnections.
> Add random string at the end of the default resource

- src/omemo/omemo.c
If OMEMO wasn't loaded, removing key would create empty identity.txt file. Then at load time it would segfault profanity.
Another commit should fix load of malformed identity.txt.
> Don't touch OMEMO cryto keys on disconnect if OMEMO wasn't loaded

- src/ui/mucwin.c
Some clients seems to send message without id.
Experienced issue with messages coming from Monal.
> Handle message without id in MUC

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/command/cmd_funcs.h
- src/config/account.c
- src/config/account.h
- src/config/accounts.c
- src/config/accounts.h
- src/config/preferences.c
- src/config/preferences.h
- src/omemo/omemo.c
- src/omemo/omemo.h
- src/ui/chatwin.c
- src/ui/console.c
- src/ui/core.c
- src/ui/mucwin.c
- src/ui/ui.h
- src/xmpp/iq.c
- tests/unittests/config/stub_accounts.c
- tests/unittests/omemo/stub_omemo.c
- tests/unittests/test_cmd_account.c
- tests/unittests/test_cmd_connect.c
- tests/unittests/test_cmd_join.c
- tests/unittests/test_cmd_otr.c
- tests/unittests/test_cmd_rooms.c
There is 3 policy:
- manual: OMEMO session are only started manually
- automatic: OMEMO session are only started if they have been started
manually before
- always: OMEMO session are always started unless they have been ended
manually before
This should fix #1040 and #1052
> Add OMEMO policy

- src/event/server_events.c
Even when opening window on message and carbon reception.
This should close #1052
> Always follow OMEMO policy 

- src/event/server_events.c
- src/xmpp/roster_list.c
- src/xmpp/roster_list.h
- tests/unittests/test_server_events.c
Presence of contact not found in roster are filtered out.
But sometimes roster is received after a first few presences.
We choose to store presences until we receive roster and then process
this presences.
This should fix #1050 
Unit test are currently failing. Once fixed PR will be mergeable.
> Handle presence received before roster

- tests/unittests/config/stub_accounts.c
- tests/unittests/log/stub_log.c
- tests/unittests/otr/stub_otr.c
- tests/unittests/ui/stub_ui.c
- tests/unittests/xmpp/stub_xmpp.c
The first commit should fix the build issues on 32-bit architectures, which debacle mentioned in the MUC.
The macro mock_ptr_type does an intermediate cast to uintptr_t which silences the compiler warnings.
The second commit is not necessary to fix the unit tests on 32-bit architectures but improve the coding style by using a similar macro to mock non-pointer types.
> Fix unit tests on 32-bit architectures

- src/command/cmd_funcs.c
The message wouldn't show up before the generation of OMEMO crypto materials started.
> Force UI update before generating OMEMO crypto materials

- src/common.c
mblen will fail with return code -1 if the locale used by the unit tests
isn't available on the machine. This will lead to an off by one error in some
tests where the needle is at the end of the haystack.
Since prof_occurrences expect null-terminated strings, the character after
the needle can simply be found by incrementing the address of the found needle
with strlen(needle).
> Don't call mblen() to not depend on locale

- src/event/common.c
- src/xmpp/iq.c
- src/xmpp/xmpp.h
- tests/unittests/xmpp/stub_xmpp.c
If Profanity is disconnected in any way before ping response is
received, the autoping timer will expire after the next connection
is established. As result, user will be disconnected immediately.
Cancel autoping timer in ev_disconnect_cleanup(), so it is done
for all kind of disconnections.
> Cancel autoping timer on disconnect or connection loss

- src/command/cmd_funcs.c
- src/plugins/plugins.c
- src/plugins/plugins.h
In case Python or C plugins are disabled install/load failed silently.
Notify the user that we can't load them because profanity was built
without support for plugins.
> Improve plugin load/install failure message

- src/command/cmd_ac.c
Some of the omemo commands depend on the roster being present.
Several of those functions call `assert()` if that's not the case.
Modify omemo autocompletion in such a way that only things that don't
need the roster will be completed. Only works on first level.
When typing `/omemo` it will still complete to `/omemo start` but not
offer suggestions for that, but print a message that you need to be
connected.
Fix https://github.com/profanity-im/profanity/issues/1117
> Only complete certain omemo commands if connected

- src/omemo/omemo.c
- src/omemo/store.c
We have to store known_devices in a long term fashion otherwise we might
not be able to delete session if it is remove from device list server
side.
Also ensure that OMEMO is removed from trusted storage.
> Remove OMEMO session when untrusting a fingerprint

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
Implements feature requested at: https://github.com/profanity-im/profanity/issues/632
So instead of:
/time console set <format>
/time chat set <format>
/time muc set <format>
/time mucconfig set <format>
/time private set <format>
/time xml set <format>
As a short cut the user can do:
/time all set <format>
Excluding statusbar and lastactivity settings since they are not for main windows, but used slightly differently.
> Add option to set all window related time formats

- src/xmpp/message.c
`message->body` was set too late.
> Fix plaintext private message handling

- src/omemo/omemo.c
- src/omemo/omemo.h
- src/profanity.c
- src/xmpp/iq.c
- src/xmpp/omemo.c
We call omemo_init() when starting profanity and should have an
omemo_close() at exit.
For now we free the fingerprint autocompleter in there.
Fixes valgrind:
```
==13226== 24 bytes in 1 blocks are definitely lost in loss record 2,855
of 6,958
==13226==    at 0x483677F: malloc (in
/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==13226==    by 0x48AD39: autocomplete_new (autocomplete.c:57)
==13226==    by 0x4AB89F: omemo_init (omemo.c:127)
==13226==    by 0x42C283: _init (profanity.c:206)
==13226==    by 0x42BFF3: prof_run (profanity.c:98)
==13226==    by 0x4B25E6: main (main.c:172)
```
Regards https://github.com/profanity-im/profanity/issues/1131
> Fix several OMEMO related leaks

- src/xmpp/blocking.c
Another case of double free() due to new destructor.
Fixes https://github.com/profanity-im/profanity/issues/1156
> Fix segfault in block command

- src/command/cmd_ac.c
- src/tools/autocomplete.c
- src/tools/autocomplete.h
Instead of only checking for files when 'last_directory' has changed, do
it every time.
Add autocomplete_update function that updates the items while retaining
last_found and search_str.
Fixes #1099
>  Always check for directory changes with sendfile auto completion

- src/xmpp/iq.c
Command form userdata were freed by iq_id_handler.
We should now free the command ourself.
Fixes #1151
> Fix command form submit

- src/xmpp/iq.c
Free form userdata used to pass command node.
> Fix memleak in /cmd exec

- src/event/server_events.c
This occured with a user running Cisco Jabber. It seems this server
sends repeated presence subscribed stanzas. And although I find this
strange according to RFC this seems to be ok.
So let's filter them and only display in the console output and to the
log. But don't open seperate windows.
Fix https://github.com/profanity-im/profanity/issues/1165
> Don't print subscribed message if contact is already in roster

- docs/profanity.1
- src/config/preferences.c
- src/config/preferences.h
- src/main.c
- src/profanity.c
- src/profanity.h
- tests/unittests/helpers.c
Introduce `profanity -c` to specify an alternative config file.
> Possibility to specify alternative config file

- src/xmpp/message.c
- src/xmpp/stanza.c
- src/xmpp/stanza.h
Double-check that a `<delay/>` tag on a groupchat message was actually added by the MUC service (rather than the sending client) before assuming it was received from the MUC history.
> Don't render (all) delayed messages as MUC history

- src/ui/statusbar.c
Should fix #1153 . @mdosch, @jubalh, please, check it.
> Don't crash if source jid doesn't contain the node part

- src/command/cmd_funcs.c
The command "/plugins install <path_to_folder> should install all
plugins in the given folder. This commit removes the check if the path
points to a file (which is repeated in the section installing a plugin
from file) and makes the existing code installing multiple plugins accessible
Fixes #1035
> Don't stop plugin installation if given path points to a directory

- src/config/preferences.c
- src/config/preferences.h
- src/ui/window.c
I just change /clear behavior, but it's not configurable. Should I implement some option for /clear, which change behavior or something like that?
> Change /clear behaviour. Closes issue #855.

- src/plugins/python_api.c
- src/plugins/python_plugins.c
ncursesw defines _XOPEN_SOURCE macro via command-line. In particular, it
is defined in ncursesw.pc and extracted via pkg-config. From other side,
Python defines the same macro unconditionally in pyconfig.h. Python-3.x
defines the macro with value different than ncursesw does. In turn, this
causes a warning that the macro is redefined. And warnings are treated
as errors.
Since both entities define the mecro unconditionally, we can't simply
reorder headers as Python developers suggest. So, undefine the macro
just before the <Python.h> to fix this silly issue.
Fixes #1203.
> plugins/python: fix double _XOPEN_SOURCE definition

- src/config/theme.c
Using "default" as color for the main window and input 
area text instead of "white" makes it better usable
with terminals using black/dark text on white/light
background while still being usable with white/light
text on black/dark background.
May fix #535
> Change default text colors to default

- Makefile.am
- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/command/cmd_funcs.h
- src/event/server_events.c
- src/xmpp/avatar.c
- src/xmpp/avatar.h
- src/xmpp/stanza.c
- src/xmpp/stanza.h
- src/xmpp/xmpp.h
- tests/unittests/xmpp/stub_avatar.c
Add the possibility to download users avatars if they were published via xep-0084.
> Download user avatars (according to xep-0084)

- src/xmpp/omemo.c
Short version: the prekey type `xs:boolean` allows `1` as true value alongside `true` but it is not currently accepted when checking whether an omemo message is encrypted with a prekey or not.
Long version: check out issue #1247 for the full motivation behind this.
> OMEMO message keys allow prekey="1" alongside prekey="true"

- src/config/preferences.c
Fix a segfault if corresponding preference is not saved in config file.
> Add default pref for PREF_COLOR_NICK

- .builds/openbsd.yml
- .travis.yml
- ci-build.sh
- configure.ac
- src/ui/rosterwin.c
- tests/unittests/test_cmd_otr.c
See my failures at: https://builds.sr.ht/~wstrm
The package cache at sr.ht is currently broken for FreeBSD, so I'll have to add that build manifest in a later PR.
How to hook it up with builds.sr.ht and GitHub:
(You need to authorize sr.ht to read from the `profanity-im` organization, too)
**On commit push hook**
* Go to https://dispatch.sr.ht
* Click `Configure new task`
* Click on `Configure task` for:
* Click `Add task` for `profanity-im/profanity`
* Save
**On PR push hook**
* Go to https://dispatch.sr.ht
* Click `Configure new task`
* Click on `Configure task` for:
* Click `Add task` for `profanity-im/profanity`
* Save
> Add builds.sr.ht CI for OpenBSD

- README.md
This PR adds a badge that show the status of the builds on builds.sr.ht. A mirror of the Profanity repository is used that is updated daily, i.e. builds are run at most once per day in case of repository updates.
> Add builds.sr.ht badge for Profanity builds

- src/command/cmd_defs.c
Some instructions were missing whitespace or punctuation.
e.g.:
were "message.Corrections" should be "message. Corrections"
> Improve formatting for some help instructions

- src/xmpp/roster_list.c
The memory leak happens when a presence is received for a MUC room. The
JID is not present in the roster, so updating its status is ignored. We
have to free resource in this case, because it has no owner and is lost
otherwise.
```
==25736== 47 (32 direct, 15 indirect) bytes in 1 blocks are definitely lost in loss record 1,625 of 3,399
==25736==    at 0x4A330FF: malloc (vg_replace_malloc.c:309)
==25736==    by 0x13A962: resource_new (resource.c:47)
==25736==    by 0x145501: _available_handler (presence.c:665)
==25736==    by 0x145501: _presence_handler (presence.c:399)
==25736==    by 0x145501: _presence_handler (presence.c:358)
==25736==    by 0x80D5F34: handler_fire_stanza (in /usr/lib64/libstrophe.so.0.0.0)
==25736==    by 0x80D2B49: _handle_stream_stanza (in …
```
> Fix memory leak of presence object

- src/ui/window.c
Profanity remembers last message and its id for the message correction
feature. We must free them in window destructor.
> Fixed memory leak in ProfMucWin

- src/ui/rosterwin.c
- src/xmpp/stanza.c
```
==5519== 32 (24 direct, 8 indirect) bytes in 1 blocks are definitely lost in loss record 1,904 of 4,424
==5519==    at 0x4A330FF: malloc (vg_replace_malloc.c:309)
==5519==    by 0x654B4A8: g_malloc (in /usr/lib64/libglib-2.0.so.0.6400.1)
==5519==    by 0x65634C1: g_slice_alloc (in /usr/lib64/libglib-2.0.so.0.6400.1)
==5519==    by 0x6567EC3: g_string_sized_new (in /usr/lib64/libglib-2.0.so.0.6400.1)
==5519==    by 0x167193: _rosterwin_resources (rosterwin.c:557)
==5519==    by 0x167193: _rosterwin_contact (rosterwin.c:407)
==5519==    by 0x16761A: _rosterwin_contacts_by_presence (rosterwin.c:244)
==5519==    by 0x168509: rosterwin_roster (rosterwin.c:130)
==5519==    by 0x147D19: _handle_chat (message.c:1220)
==5519==    by 0x147D19: _message_handler (message.c:154)
==5519==    by …
```
> Fix few memory leaks

- src/xmpp/stanza.c
The function creates a form to find such strings as software, os, etc.
It remembers the strings allocated by form_create() and use them below
in caps_create(). The issue is that the form is destroyed before and as
result the strings are freed too.
As solution, allocate own copy of strings.
> Fix use-after-free in stanza_create_caps_from_query_element()

- src/common.c
- src/ui/notifier.c
glib functions can allocate a GError object that must be freed with
`g_error_free()`. Otherwise a memory leak happens.
There are similar unfixed places in omemo, check:
```
grep "&error" src/omemo/omemo.c
```
Fixes #1304.
> Free GError objects

- src/xmpp/muc.c
Profanity request the OMEMO Device List for all members, also if the MUC is
anonymouse. If the user is Admin / Owner, the device list will be requtest.
Issue #1315
> OMEMO Device List only for non anonymous MUCs

- src/command/cmd_defs.c
Add missing whitespace and mention how /correct and /correction are related.
> Mention the related commands for /correct and /correction

- src/event/server_events.c
There is code to redraw the ui, because the user may enter a passphase for the
private key. There was also a ui_init, which shouldn't be called, because it
will set the status to the initial state, which is 'offline' and 'no tls'.
Issue: #1327
> Bugfix: Status with PGP shows offline in titlebar

- src/xmpp/iq.c
A autoping is to make sure that there is still a connection between server and
client. If the application receives incoming stanza, the connection is fine.
There is no need to wait for response, if there are other incomings.
Issue: #1333 and #1315
> Incoming iq stanza - Reset the autoping timer

- src/xmpp/omemo.c
NOTE: as per XEP-0060 §12.20, it is RECOMMENDED for the publisher to specify an
ItemID of "current" to ensure that the publication of a new item will overwrite
the existing item.
https://xmpp.org/extensions/xep-0384.html#devices
Issue: #1329
> OMEMO - Request only "current" item

- configure.ac
After the library is found by pkg-config, try to build a simple program
to check the installation. The motivation of this check is that the
chance that users manually install libstrophe/libmesode is higher than
for other libs.
Fixes #1334.
> configure.ac: add additional check for libstrophe

- configure.ac
without this, i receive this error on openbsd 6.7:
src/event/server_events.c:1477:19: error: universal character names are only valid in C++ and C99
src/event/server_events.c:1478:19: error: universal character names are only valid in C++ and C99
gmake[1]: *** [Makefile:1925: src/event/server_events.o] Error 1
gmake[1]: Leaving directory '/home/toogley/profanity'
gmake: *** [Makefile:1212: all] Error 2
> use always c99; fixes "universal character names" error msg

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/config/account.c
- src/config/account.h
- src/config/accounts.c
- src/config/accounts.h
- src/event/client_events.c
- src/event/client_events.h
- src/ui/console.c
- src/xmpp/connection.c
- src/xmpp/connection.h
- src/xmpp/session.c
- src/xmpp/xmpp.h
- tests/unittests/config/stub_accounts.c
- tests/unittests/test_cmd_account.c
- tests/unittests/test_cmd_connect.c
- tests/unittests/test_cmd_join.c
- tests/unittests/test_cmd_otr.c
- tests/unittests/test_cmd_rooms.c
- tests/unittests/xmpp/stub_xmpp.c
New options:
/connect <account> [auth default|legacy]
/account <account> set auth default|legacy
Fixes #1236.
> Add option for legacy authentication

- configure.ac
- src/xmpp/connection.c
Some systems don't provide recent libstrophe releases. When older
version of libstrophe is detected, don't build legacy auth support.
To simplify this patch, report about unsupported legacy auth and
keep commands option as is.
/!\ This patch adds `ui/ui.h`. Is it ok?
> Make legacy auth optional

- src/xmpp/message.c
Check for pointer to be NULL before dereferencing it.
> Fix possible segfault in xmpp/message.c

- src/tools/bookmark_ignore.c
> Add missed string.h

- src/ui/notifier.c
strncpy(3) is not so safe function and can lead to mistakes. For
example, strncpy(dest, "Profanity", 10); is redundant and leads to
problems when someone changes the source string.
Different example is when 3rd argument equals to length of the
destination buffer. strncpy(3) doesn't terminate string with '\0' when
it truncates. Therefore, the destination string becomes corrupted.
Zeroize storage for 'nid', so the last byte remains '\0' in case of
truncate.
> Fix gcc warnings for cygwin

- src/event/server_events.c
- src/xmpp/message.c
Fix for some build cases introduced in 2c94ee5a88f64332a3f41f41a4d314fc52200e31
Fix https://github.com/profanity-im/profanity/issues/1376
> And ifdefs around new OX functions

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/command/cmd_funcs.h
- src/config/preferences.c
- src/config/preferences.h
- src/ui/console.c
- src/ui/window_list.c
This PR includes the (rebased, organized and squashed) commits from @pmaziere from his repo https://framagit.org/peetah/profanity/ revampUrlopen branch.
It is about https://github.com/profanity-im/profanity/issues/1361 with the purpose of  defining external commands to open and save URLs according to file types and protocols.
One benefit of this is that it will allow users to download and decrypt OMEMO file extensions using [omut](https://github.com/wstrm/omemo-utils).
> Rework /url and /executable for filetypes

- src/xmpp/message.c
Messages from Conversations contains:
```<request xmlns='urn:xmpp:receipts'/>```
And would not be displayed in Profanity as it never reached
_handle_chat(..).
> Fix messages with receipt request not displayed

- src/xmpp/message.c
We basically had a lot of duplicate code in _handle_chat() and _handle_carbons().
I try to improve the situation.
There is still more to be done. But I would like to get a review of it as is, just to make sure that I'm keeping the old behaviour.
Added some TODOs for more stuff that I need to check later on.
> Cleanup carbons/chat handling in message.c

- src/omemo/omemo.c
Profanity requests the device list and keys for contacts, also when the user
hasn't generated the OMEMO key. If the user has no OMEMO key, there is no need
to request OMEMO information.
Issue: #1332
> Request Device and Key, when OMEMO is in use

- src/config/account.c
All errors were discarded to /dev/null if the error_ptr was set to
NULL.
> Log errors from eval_password

- Dockerfile.arch
This is required because of:
https://www.archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/
> Change to .tar.zst archives that latest Arch devtools uses

- configure.ac
Make Profanity compilable with gtk2 and gtk3.
Prefer the latter.
> configure: support gtk3 too

- configure.ac
- src/common.c
- src/config/color.c
- src/config/theme.c
- src/ui/buffer.c
- src/ui/console.c
- src/ui/core.c
- src/ui/inputwin.c
- src/ui/rosterwin.c
- src/ui/screen.c
- src/ui/statusbar.c
- src/ui/win_types.h
- src/ui/window.c
- src/ui/window.h
The following changes were required:
- Added NetBSD as a platform that does not have a separate `libdl` to `configure.ac`.
- Changed a `==` condition in `configure.ac` to use `=` instead. These are identical, it's just that `=` is in POSIX and `==` isn't. NetBSD's `/bin/sh` only supports the POSIX syntax.
- Recognize NetBSD `libcurses` as a valid curses implementation.
AFAIK, NetBSD is now the only operating system that does not primarily use ncurses. Its own curses library has support for wide characters and similar features -- there's also a [port of it to Linux](https://github.com/sabotage-linux/netbsd-curses).
- NetBSD curses is less permissive when handed null pointers than ncurses, apparently. I had to add a few checks to avoid null pointer deref.
Notes for building profanity on …
> NetBSD support

- src/ui/console.c
Commit f12161f fixes memory leak, but introduces use-after-free issue.
Allocate new memory for win_name with g_strdup() since it is freed with
g_free() later.
> Fix use-after-free which is introduced in cons_alert()

- src/config/scripts.c
- src/database.c
- src/omemo/omemo.c
- src/pgp/gpg.c
- src/ui/inputwin.c
- src/xmpp/avatar.c
This is just a very minor issue.
profanity contains some calls to strerror where the result is assigned to a char *. However, according to the strerror specification, the string returned by strerror should never be changed, so I think it would be better to use const char * instead.
Philipp
> Since the string from strerror should never be modified, use const.

- src/xmpp/bookmark.c
When a bookmark is created with '/bookmark add' command,
ext_gajim_minimize remains uninitialised in new bookmark object and
is read further in _send_bookmarks().
Initialise the field with 0.
Fixes #1432.
> xmpp/bookmark: don't use uninitialised field

- Makefile.am
- RELEASE_GUIDE.md
- docs/profanity.1
- src/command/cmd_defs.c
- src/command/cmd_defs.h
- src/main.c
`profanity mangen` will create for each command (`/account`, `/roster`)
an own manpage (`profanity-account.1`, `profanity-roster.1`)
See https://github.com/profanity-im/profanity/issues/1444
> Create cmd to generate man pages for prof commands

- src/event/server_events.c
Doesn't make sense to log if plain is not set in all cases.
Regards https://github.com/profanity-im/profanity/issues/1439
> Fix chatlogs for outgoing carbons

- src/config/theme.c
There is a small typo in src/config/theme.c.
Should read `certain` rather than `certian`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, certian -> certain

- src/command/cmd_funcs.c
- src/tools/http_download.c
* If the downloads directory does not exist, create it.
* Change some cons_show to cons_show_error (because they log errors).
* There was a deadlock that occured if an error occurs before HTTP download had begun, e.g. if fopen returned an error.
> Create download directory under XDG data path

- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/config/files.c
- src/log.c
- src/log.h
- tests/unittests/log/stub_log.c
`profanity -f my` created ~/.local/share/profanity/logs/my.log`.
It would be nicer if one could define the actual path, so one can choose
another directory or even use /dev/null.
Fixes https://github.com/profanity-im/profanity/issues/1442
> Use whole path as logfile when defined via -f

- src/ui/window.c
Discovered by @aba-hollerer.
Mistake was introduced in b6b7dd5ad497a71e250b8b3cef0bb987314b141d
probably due to a wrong copy/paste.
First wasn't reproducible because I had `/receipts request on` and thus
win_print_outgoing_receipts() is used which has the correct
THEME_TEXT_ME.
> Fix color for win_print_outgoing()

- src/ui/window.c
Remove added blank line after trackbar, introduced by 606c1e51e688cb111b9837579a35460508324b63, fixes #1457
> Remove blank line after trackbar

- src/ui/inputwin.c
Input window size was one cell off, therefore terminal themes with background color set were rendered incorrectly, fixes #1458
> Set input window size to max window size

- ci-build.sh
Because we trap the error signal and run a error handler, logs were not
printed. I moved the printing of test-suite.log to the error handler and
also added so that config.log is printed on failure.
> Print logs on error in CI

- src/ui/window.c
Error log:
GLib-CRITICAL - g_string_insert_len: assertion 'len == 0 || val != NULL' failed
Check if a room name exists, before adding the name into the title bar.
> Bugfix: Titlebar show name without room name

- src/database.c
On every write to `chatlog.db` syslog throws
```
profanity: vfprintf %s NULL in "INSERT INTO `ChatLogs` (`from_jid`,
`from_resource`, `to_jid`, `to_resource`, `message`, `timestamp`,
`stanza_id`, `archive_id`, `replace_id`, `type`, `encryption`) SELECT
'%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s' WHERE
NOT EXISTS (SELECT 1 FROM `ChatLogs` WHERE `archive_id` = '%s')"
```
in `/var/log/messages`. Checking for `NULL` except in the fields the DB
is expected to throw errors for, satisfies OpenBSDs security measures
> Calm OpenBSD syslog

- src/ui/core.c
This change simplifies wintitle so that it uses libc fputs and fprintf to draw the X-window titles instead of shelling out to /bin/echo.
I've tested wintitle show and goodbye on Void linux (glibc) with both rxvt-unicode and xterm.
> Draw wintitle using fputs and fprintf instead of /bin/echo.

- src/common.c
Rationale: When copying an image in some application, a URL instead of a
path is copied to the clipboard.
> Remove "file://" from file names

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/xmpp/iq.c
- src/xmpp/stanza.c
- src/xmpp/stanza.h
- src/xmpp/xmpp.h
- tests/unittests/xmpp/stub_xmpp.c
`/affiliation register` can now be used to register a nickname with a
MUC.
Tested with a server without forms. Couldn't find a server which
supports forms yet.
> Register nickname with MUC

- src/database.c
- src/event/server_events.c
- src/xmpp/avatar.c
- src/xmpp/iq.c
- src/xmpp/message.c
- src/xmpp/ox.c
- src/xmpp/stanza.c
Inspired by https://github.com/profanity-im/profanity/issues/1509 I started something which I have on my TODO list since a long time. Looking for places where profanity could crash when we can malformed stanzas. Things were we expect the sending entity to follow the spec and would so far crash if they don't.
> Fix potential problems caused by unexpected stanzas

- src/command/cmd_funcs.c
- src/event/client_events.c
- src/omemo/omemo.c
- src/ui/chatwin.c
>  [OMEMO] Fix sending messages

- src/ui/chatwin.c
I find it helpful to have the plugin hook pre_chat_message_display apply to messages shown in a chat's history (via _chatwin_history) and not just for new incoming messages (in chatwin_incoming_msg). There is just one line here but I can try and add some tests or anything else if someone thinks it would be useful.
Could this break any current plugins?
On a related note, a similar change could be made to pre_room_msg_display
> Apply pre_chat_message_display hook to history

- src/omemo/omemo.c
- src/omemo/store.c
- src/xmpp/message.c
- src/xmpp/omemo.c
The most loggings has been set to debug. Just in case of error / problem the
logging should be done with log-level ERROR or WARNING.
We will see later, which loggings should be switched to log-level INFO.
This improvement has been done to find OMEMO bugs.
See also: #1070 #1530 #1538
> Improved OMEMO logging

- src/command/cmd_funcs.c
- tests/unittests/omemo/stub_omemo.c
Display the OMEMO device ID which has been generated, when the user generated
OMEMO crytographic materials via /omemo gen.
> Display OMEMO device ID

- src/omemo/omemo.c
- src/xmpp/omemo.c
If we are not able to publish our own device list, we just ignored it.
This commit will show at least an error message and informs the user that this
device is currently not in the list of devices.
See Issue: #1538
Next task will be to handle the <precondition-not-met/> conflict properly.
> OMEMO - Unable to publish own device list

- src/ui/window_list.c
When the connection has been re-established, chat and groupchat with OMEMO
should restat the OMEMO Session.
Fix: #1530
> Restart OMEMO Session after lost connection

- src/omemo/omemo.c
As defined in XEP-0384 the application should not encrypt the message to own
devices. Within a groupchat, yourself are a recipients as well.
We will check the recipients and filter out the own device of the own jid.
This Pull Request will fix Issue: #1541
> OMEMO: Don't encrypt to yourself (MUC)

- src/xmpp/message.c
This is not an error, the message has no body because of
XEP-0085: Chat State Notifications.
Changed log level from error to info.
> Message received without body error log

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/ui/console.c
- src/ui/ui.h
- src/xmpp/bookmark.c
- src/xmpp/xmpp.h
- tests/unittests/ui/stub_ui.c
- tests/unittests/xmpp/stub_xmpp.c
`/bookmark list` lists all bookmarks with its details.
`/bookmark list <jid>` shows the details of a single bookmark.
Implement https://github.com/profanity-im/profanity/issues/1558
> Add command to show single bookmark details

- src/log.c
See https://github.com/profanity-im/profanity/issues/1518
It has a good explanation of what happened:
```
Apparently, the _rotate_log_file function tried to extract user-provided
name from currently used mainlogfile and restart logging to the same
place after rotation, but currently this is interpreted as a full path
instead. As I understand, the log rotation is no longer done with
user-provided paths at all so this should be simply skipped altogether
now as passing any non-NULL value is interpreted as user-provided.
Replacing start with NULL appears to fix it for me.
```
In log_msg() we only rotate the log if not user_provided_log.
https://github.com/profanity-im/profanity/pull/1455 changed the
behaviour from user defined filename in the log dir to using full path.
> Fix log rotation

- src/config/preferences.c
Since I didn't find a way to discover whether a notification server is
running I decided to disable them by default. So people without one will
not have such a bad lag due to timeout from libnotify.
Fix https://github.com/profanity-im/profanity/issues/977
> Disable notifications by default

- apidocs/c/profapi.h
- apidocs/python/src/prof.py
- src/plugins/api.c
- src/plugins/api.h
- src/plugins/c_api.c
- src/plugins/profapi.c
- src/plugins/profapi.h
- src/plugins/python_api.c
- src/xmpp/roster_list.c
- src/xmpp/roster_list.h
- tests/unittests/test_roster_list.c
- tests/unittests/test_roster_list.h
- tests/unittests/unittests.c
This adds two functions to the "prof" plugin API:
```c
char* prof_get_name_from_roster(const char *barejid);
```
and
```c
char* prof_get_barejid_from_roster(const char *name);
```
as well as the equivalent functions for the Python API.
I can add some tests if this functionality is otherwise mergable and of course fix anything else too!
There is a potential inconsistency here because these functions inherit the convention of the `xmpp/roster_list.c` functions that they call. `prof_get_name_from_roster` returns the input barejid if it is not found in the roster, but `prof_get_barejid_from_roster` returns NULL if the name is not in the roster. This makes sense to me but is potentially confusing.
> Access roster from plugins

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/command/cmd_funcs.h
- src/config/preferences.c
- src/config/preferences.h
- src/ui/console.c
- src/ui/ui.h
- src/xmpp/message.c
- tests/unittests/ui/stub_ui.c
`/silence on` will throw away all messages (type: chat, normal) that
come from jids that are not in the roster.
Implement https://github.com/profanity-im/profanity/issues/955
> Add option to only allow messages from jids in roster

- src/ui/mucwin.c
_mucwin_print_mention() leads to invalid reads:
```
==18478== Invalid read of size 1
==18478==    at 0x4B7D840: g_utf8_offset_to_pointer (in /usr/lib64/libglib-2.0.so.0.6600.4)
==18478==    by 0x4B7D8DF: g_utf8_substring (in /usr/lib64/libglib-2.0.so.0.6600.4)
==18478==    by 0x16C29A: mucwin_incoming_msg (in /usr/bin/profanity)
==18478==    by 0x1524F7: sv_ev_room_message (in /usr/bin/profanity)
==18478==    by 0x146F4F: _message_handler (in /usr/bin/profanity)
==18478==    by 0x511175C: handler_fire_stanza (in /usr/lib64/libstrophe.so.0.0.0)
==18478==    by 0x510DECA: _handle_stream_stanza (in /usr/lib64/libstrophe.so.0.0.0)
==18478==    by 0x511CAEE: _end_element (in /usr/lib64/libstrophe.so.0.0.0)
==18478==    by 0x5812982: doContent (in /usr/lib64/libexpat.so.1.6.12)
==18478==    by …
```
> Fix invalid reads on mentions in MUC

- src/config/accounts.c
- src/event/server_events.c
`g_key_file_get_string()` returns a newly allocated string and must be freed with g_free(). `accounts_get_login_status()` uses this API internally and also for return value.
Also reduce copy-paste in a separated commit. Please, review this part carefully.
> Fix memory leak in accounts_get_login_status()

- src/ui/chatwin.c
_chatwin_history() reassigns msg->plain without freeing previous string. This leads to memory leak. As a temporary solution, free replaced string.
Fixes #1585.
> Fix memory leak in chatwin when load history (#1585)

- src/omemo/omemo.c
- src/xmpp/omemo.c
- src/xmpp/omemo.h
- src/xmpp/stanza.h
Fix #1538
Handle precondition-not-met returned when inserting our device in the device list. Try to reconfigure it properly and give up if it fails again.
Also add support for missing device list node. It rely on auto-create. We should ensure this feature is enabled and fallback to a proper create with config otherwise.
> Fix OMEMO devicelist access model by reconfiguring it

- src/command/cmd_funcs.c
On non-glibc systems, libcurl fails to read the OMEMO encrypted file when it is opened in `"wb"` mode (as is expected). Changing it to `"w+b"` allows `profanity` to `/sendfile` in OMEMO encrypted chats on BSDs and musl based Linux distributions.
Fixes #1478
> Fix OMEMO /sendfile on non-glibc systems

- configure.ac
Currently, `configure.ac` assumes Readline is installed via Homebrew in
`/usr/local`. This doesn't work for Homebrew on Apple Silicon, or
MacPorts.
Let's fix this by checking for a `brew` installation, and querying that
for Readline's prefix if available. If not, check for an existing
MacPorts prefix, and finally fall back to `/usr/local` in case a user
installed Readline for themselves there.
Closes #1612.
> Make readline check more portable

- src/xmpp/message.c
- src/xmpp/stanza.h
We came into the carbons checking code when we received `<private
xmlns="urn:xmpp:carbons:2"/>`. Which actually marks a message to _not_
be a carbon.
In this code we also make sure that carbons only come from us.
If not we don't call the message handler code.
So we should actually only check for `<sent xmlns='urn:xmpp:carbons:2'>`
and `<received xmlns='urn:xmpp:carbons:2'>`.
Thanks pukkamustard and Holger.
Fixes https://github.com/profanity-im/profanity/issues/1614
> Fix carbons criteria

- src/omemo/omemo.c
Previously the device list was appended with the set of sender devices only after key generation. This pull request proposes a fix so these sender devices are included before sessions are started. That means after identity has been loaded or generated.
This fixes the problem with message encryption to sender devices. Profanity does not send any message to such devices because it does not even know they exist.
See the issue https://github.com/profanity-im/profanity/issues/1609
Tested with both identity loading and identity generation with `profanity` + `blabber-im` on `prosody` (additional info just in case). Seems to work. Anyway needs more observance.
> Fix message encryption for sender devices

- Makefile.am
use wildcard for man pages in Makefile.am
otherwise it did not build on Debian, see https://salsa.debian.org/xmpp-team/profanity/-/blob/debian/master/debian/patches/fix-make-globbing.patch
> use wildcard for man pages in Makefile.am

- .builds/openbsd.yml
- ci-build.sh
GCC is disabled in 7.0, so instead we install it explicitly and point the CC variable to egcc (which is the binary of the gcc package installed with pkg_add).
> Upgrade to OpenBSD 7.0 in CI

- src/database.c
The original intention of the code was that in case archive_id is not set, NULL should be inserted. What is
inserted however is an empty string. This causes the condition to not insert messages with non-unique
archive_id insert only one message in total and ignore all further ones (if NULL was there, the condition
would work properly). And this in turn causes chat history not work properly.
This commit makes the SQL condition work properly and therefore fixes chat history.
Fixes #1589.
See https://github.com/profanity-im/profanity/issues/1589#issuecomment-1002290945 for longer explanation.
> database.c: fix inserting messages to chat logs if archive_id is empty

- src/xmpp/session.c
When a `see-other-host` stream-error is received we try to re-connect to
the other host. Erroneously this also started the `reconnect_timer`.
This lead to the behavior that in cases where e.g. the login failed
we try to reconnect instead of bailing out with an error.
This commit fixes the wrong behavior by not starting the `reconnect_timer`.
Fix 0e58509c161ae8409c9accabb9606e0c7006b880 
Related to #1628 #1631
> fix handling of connection errors

- Makefile.am
- src/command/cmd_funcs.c
- src/command/cmd_funcs.h
- src/tools/editor.c
- src/tools/editor.h
- src/ui/inputwin.c
Add a hotkey for sending text in readline to external text editor.
Should deprecate the need for /command-editor requests like /subject-editor, /correct-editor.
Example workflow:
alt+d to open editor or write something in readline first and then alt+d.
I have a feeling a put the declaration of _get_message_from_editor in a suboptimal header file.
> Add hotkey for sending readline text to editor

- src/ui/inputwin.c
Remove check for '/' at the beginning of the line before autocompleting
and make it fallback to command autocompletion if no nicks found.
Fixes https://github.com/profanity-im/profanity/issues/1474
> Fix not autocompleting nicks with '/'

- src/tools/editor.c
Calling /editor crashes profanity.
This fixes that
> Fix crash on /editor

- src/command/cmd_funcs.c
I guess we should reset the position after we ran `/url open|save`.
So that next time `/url open <tab>` starts with the latest entry.
Fix https://github.com/profanity-im/profanity/issues/1654
@MarcoPolo-PasTonMolo I guess this is what we want?
> Reset url autocompletion after open/save

- src/config/preferences.c
When preferences do not specify a program to be used for /editor
command, try getting it from EDITOR (which POSIX.1-2017 calls one of
"variables that are frequently exported by widely used command
interpreters and applications"), fall back to "vim" if not set.
> Use EDITOR environment variable

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/ui/mucwin.c
Fixes https://github.com/profanity-im/profanity/issues/1425
`/who none` now displays all users in an muc without an affiliation
> Add none option for /who

- configure.ac
Option -ggdb3 (same as -g3) doesn't affect code-generation, just adds
to the binary size of an executable. Automake strips installed
binaries automatically when "make install-strip" is run so enabling
this option permanently doesn't affect the end result while allowing
for hassle-free interactive debugging.
If one is running a stripped binary it's still possible to attach GDB
by process PID and then use "file /path/to/unstripped/profanity" to
get all symbols and lines data.
> Add debug information to binary

- src/ui/inputwin.c
The current code enters an infinite loop if the input string happens
to get an invalid utf-8 sequence somehow. For me it was reproducible
by running profanity in a Screen session and pressing Alt-т (cyrillic
letter).
Fix it the way borrowed from 0501e49623f68aa39508e4e622924c1dd8147588
where mbrlen is used for the same purposes.
> Input window: handle invalid multibyte

- src/ui/core.c
The current code is inherently racy: if screen update takes
considerable time (e.g. when working over network) and a user
performed a series of resizes the final event might get ignored and
the display will be left in inconsistent state.
Fix the race by unsetting the flag first so if the next WINCH signal
is received while display is resizing it'll be processed on the next
iteration.
> Fix race condition on resize

- src/ui/inputwin.c
GNU Screen terminal emulator is modelled after VT100, its key bindings
for "application mode" (which profanity enables on startup) can be
seen with this: info screen "Input Translation".
> Add Alt/Ctrl-arrows combinations for GNU Screen

- src/log.c
Reported by @akawolf in profanity@rooms.dismail.de
Logs created while this bug was active were stored in `/home/<user>/.local/share/profanity//home/<user>/.local/share/profanity/chatlogs/`
> fix path where logs are stored

- src/config/theme.c
disable execution of colors-changing code when call for theme load and it doesn't exist
> fix theme load

- profrc.example
Since some other commands are using british spelling for colour it
makes sense to have it available for /color command as well.
IRC users will feel more at home having /topic command equivalent to
/subject (which seems to be a MUC-specific terminology).
> Include useful aliases in profrc example

- src/command/cmd_funcs.c
- src/ui/inputwin.c
When editing multi-line messages or comments everything past the first
newline becomes invisible.
This patch fixes it by substituting a Unicode symbol for "return"
instead of printing the newline as is. On locales where it's not
available single backslash is used instead.
> Show return symbol for embedded newlines

- configure.ac
Using pkg-config to find libraries requires explicit mention of the
relevant _CFLAGS and _LIBS variables.
Fixes #1695.
> Fix xscreensaver detection

- src/command/cmd_funcs.c
- src/xmpp/ox.c
Fix https://github.com/profanity-im/profanity/issues/1698
> Fix SIGABRT when using wrong argument order for receiving ox key

- src/log.c
Let's use ISO8601 in our chatlogs and log files.
Chatlogs are at:
`~/.local/share/profanity/chatlogs/me_at_domain.org/other_at_domain.org/YYYY_MM_DD.log`
Log files are at:
`~/.local/share/profanity/logs/profanity.log`
> Use ISO8601 as date format in log files

- src/command/cmd_defs.c
- src/config/preferences.c
In case chatlogs are available lets log everything by default.
Seems like most users expect this behaviour and I agree.
> Log encrypted messages by default to chatlog

- src/xmpp/iq.c
Now whenever the name of a room changes, either in profanity or another
client, it gets updated inside profanity.
Fixes https://github.com/profanity-im/profanity/issues/1710
> Fix room name not updating.

- src/xmpp/ox.c
`/ox discover` segfaults on some misconfigured? nodes because there are
newlines before and after some pubkey-metadata stanzas so the newlines
get treated as seperate stanzas. This commit just skips each stanza in
public-keys-list that doesn't have a fingerprint.
Fixes https://github.com/profanity-im/profanity/issues/1713
> Fix segfault on `/ox discover`

- src/xmpp/presence.c
Profanity would ignore the silent nick change in some places. The roster
and history would show the correct nick, new messages from the current
user and the "Autojoined <jid> as <nick>" message would show the wrong
one. This commit fixes that problem.
Fixes https://github.com/profanity-im/profanity/issues/757
> Respect silent nick change in mucs

- src/xmpp/iq.c
- src/xmpp/message.c
Updates whether the muc is members only and its anonymity type.
Problem: the caps request is not always sent, it is always sent when name of muc is changed but not if the members only or anonymity type is changed. Any tips?
Should fix 1347 when completed
> Update capabilities of muc on available presence

- Dockerfile.arch
- Dockerfile.debian
- Dockerfile.fedora
- Dockerfile.tumbleweed
- Dockerfile.ubuntu
- ci-build.sh
- configure.ac
- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/main.c
- src/xmpp/avatar.c
- src/xmpp/avatar.h
- src/xmpp/stanza.c
- src/xmpp/stanza.h
- tests/unittests/xmpp/stub_avatar.c
Use `/avatar set <path>` where <path> is an image file to upload a new
avatar for the current user. When the avatar is too big it gets scaled
down. Scaling code copied from dino.
Not so sure about using `gdk_pixbuf_save_to_buffer` because it's available after 2.4
Fixes https://github.com/profanity-im/profanity/issues/1687
> Add `/avatar set` command to publish avatar

- src/ui/window.c
- src/xmpp/message.c
Messages would get duplicated when you chat with yourself, worse if you
had omemo enabled the duplicated message would say something along the
lines of "Your client doesn't support OMEMO". The cause was carbons
when the message was sent from another client, whilst it was a sent
and received message when profanity was the one to send it. This commit
ignores the carbon message in the 1st case and ignores the received one
in the 2nd.
Fixes https://github.com/profanity-im/profanity/issues/1595
> Fix duplicate messages in chat with oneself.

- src/tools/parser.c
"" used to become " now it just becomes an empty argument.
Also if quotes appeared after a token started then if the number of
quotes in the token is n the resulting one would be a token with the
n last characters cut off, now it's fixed.
Fixes https://github.com/profanity-im/profanity/issues/497
> Improve cmd argument parser

- src/ui/window.c
If we are in a window with a lot of text and press PAGE UP we scroll up
and write [scrolled] in the titlebar.
So far we also wrote [scrolled] in there even when actually nothing
happened. Like when opening a new window (/msg someone) and there is no
text inside.
> Don't scroll if not needed

- src/event/server_events.c
- src/ui/chatwin.c
- src/ui/mucwin.c
- src/ui/privwin.c
Most likely some strange message was received.
Let's add a message-> plain check in the print functions for incoming messages for each window.
And in case we didn't get a text from the OX message in message->plain let copy over the one from the body. Like we do for pgp and others as well.
> Be more resilient when receiving empty messages

- src/command/cmd_funcs.c
Two issues were fixed in the parser logic:
* A call to cons_bad_cmd_usage() was placed at the end of the "time"
parser section that blocked reachability to both "message" and
"check" parser sections. This caused "/autoaway message ..." and
"/autoaway check ..." to always fail with "Invalid usage". This
issue was introduced in commit 3c1e4ba.
* "/autoaway message xa" with no message argument returns message
set to (null). This should be fixed the same way as
"/autoaway message away" was fixed in commit 3c1e4ba.
> Fix /autoaway command logic

- profanity.doap
```
$ xmllint profanity.doap
profanity.doap:43: namespace error : Namespace prefix foaf on Person is not defined
<foaf:Person>
^
profanity.doap:44: namespace error : Namespace prefix foaf on name is not defined
<foaf:name>Michael Vetter</foaf:name>
^
profanity.doap:45: namespace error : Namespace prefix foaf on homepage is not defined
<foaf:homepage rdf:resource="https://iodoru.org/"/>
^
```
> doap: fix missing foaf namespace prefix

- src/common.c
- src/xmpp/avatar.c
In issue #1742 the reason behind crashing is supposedly undefined behavior because it was observed by me, `g_spawn_sync` may not modify `spawn_error` pointer. When I was debugging, it was pretty random and its value didn't fall into any of mapped memory regions.
`spawn_error` pointer was not null and code tried to read its field but this caused segfault instantly. I believe there was no message because for some reason glib did not set it to some value (there was an error!).
Though the basis for that is because mentioned `gio open` was considered to be one argument, it was failing to find such program and hence `g_spawn_sync` returned an error to that.
So this fixes undefined behaviour for that pointer and moreover made both pointers null by default just in case. Not sure why glib does not …
> Fix for avatar opening executable

- configure.ac
Otherwise gdk-pixbuf is always added as dependency even if disabled, when found.
> typo in configure: enable_gdk_pixbuf not enable_pixbuf

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
* The `/plugins uninstall` command  <__without plugin name__>  behave same as `/quit`. I'm not sure that it was so conceived.  dd1a9a1e in this case  displays a hint, without exit.
* For the `/plugins` command  <__without args__> 45fa60e7 add to output the list plugins which have already been installed, but  unloaded  (If there are such).
> Fix plugins managment

- src/plugins/python_api.c
From Python 3.11, PyFrameObject has been changed into opaque struct. We need to access those fields via API.
Signed-off-by: Đoàn Trần Công Danh <congdanhqx@gmail.com>
> plugin: python: fix build for Python 3.11

- src/ui/console.c
Only display help message on first start.
This is a fixup for:
https://github.com/profanity-im/profanity/commit/27a5c9d287e856bd774988b4066667db54b65de7
> Fix first start detection

- src/command/cmd_funcs.c
- src/common.c
- src/common.h
- src/tools/aesgcm_download.c
- src/tools/http_download.c
- src/xmpp/avatar.c
The original `call_external` is kept as `call_external_sync`
Fixes #1759
> Replace `call_external`'s implementation with an async one

- src/command/cmd_ac.c
Let /win and /msg both autocomplete roster nickname and actual barejid
> Improve /msg and /win autocompletion

- src/database.c
- src/database.h
- src/event/server_events.c
- src/ui/buffer.c
- src/ui/buffer.h
- src/ui/chatwin.c
- src/ui/ui.h
- src/ui/window.c
- src/ui/window.h
- src/xmpp/iq.c
- src/xmpp/stanza.c
- src/xmpp/stanza.h
- src/xmpp/xmpp.h
Started trying to finish MAM here's what I've done so far. Nowhere near production ready btw. Many temporary stuff in here.
* When we open new chat (`/msg someone`) if no msgs in db fetch using before: now. else fetch after most recent one.
* When scrolled to top, fetch older messages from db and display them above the previous ones.
* After all db history gets displayed when scrolling up, fetch older messages from mam (these ones get displayed after everything instead of before)
Todo:
* Only fetch once if no msgs for one chat (further fetching will be done when scrolling).
* MAM for mucs
* Have different pagination counters for each chat (currently one temporary global one)
* When scrolling up display new mam messages before other ones instead of after. (start of buffer instead of end)
* …
> MAM improvements

- src/ui/window.c
When loading messages from MAM profanity would segfault. Reason was that we were freeing the timestamp of messages when displaying them and we needed it for loading MAM.
> Fix segfault when loading from MAM

- src/ui/window.h
Replaced three dots `...` by a proper ellipsis `…`.
Removed plenking (space between `messages` and ellipsis.
> Improve MAM loading string.

- src/config/color.c
Locally I have clang-format 15.0.2.
Our CI runs ubuntu-20.04 so it has 10.0.
Seems like a default value changed but I can't find it. When I still had clang-format 14.x everything was fine and checking: https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#clang-format
I only see irrelevant things.
Someone on the llvm IRC channel sais "there is no guarantee" and "maybe a regression or intended change".
But seems like noone knows which setting could be the one we need.
Since I don't have a better solution for now I will just edit this by hand to apply to the clang-format version we have on the CI. Will look into updating this one.
But in any case it would be best if the configuration file could have this setting so formatting works the same for all contributors.
> Work around different clang-format versions

- src/command/cmd_ac.c
Previously after the url if you pressed tab, even if you typed out a filepath, profanity would erase that and cycle through url autocomplete results.
This patch solves that and autocompletes filepaths after the url.
Fixes https://github.com/profanity-im/profanity/issues/1783
> Make `/url save` autocomplete filenames after a url

- src/common.h
- src/omemo/omemo.c
- src/xmpp/message.c
- src/xmpp/omemo.c
Hi,
OpenBSD's kernel warns about NULL printfs.  Currently, the following messages appear in the system's logs:
```
Jan  6 10:30:53 kronos profanity: vfprintf %s NULL in "[OMEMO] Setting device list for %s"
Jan  6 10:30:53 kronos profanity: vfprintf %s NULL in "[OMEMO] omemo_start_device_session_handle_bundle: %s"
```
Fix this by checking if the variable is indeed NULL and print an empty string instead. There might be more places in the code where this happened, these are the ones that I got warning so far.
Cheers
> Don't pass NULL pointers to vprintf

- src/tools/autocomplete.c
- src/tools/autocomplete.h
- src/ui/chatwin.c
- src/ui/mucwin.c
- src/ui/privwin.c
- src/ui/window.c
- src/ui/window_list.c
- src/ui/window_list.h
After adding MAM quote and url autocompletion wouldn't pick up messages from MAM or history(from DB) or would have them in the wrong order. This commit fixes that.
Fixes https://github.com/profanity-im/profanity/issues/1770
> Fix quote and url autocompletion for MAM and history

- src/command/cmd_funcs.c
- src/tools/aesgcm_download.c
- src/tools/aesgcm_download.h
- src/tools/http_common.c
- src/tools/http_common.h
- src/tools/http_download.c
- src/tools/http_download.h
- src/ui/window.c
- src/ui/window.h
- tests/unittests/tools/stub_aesgcm_download.c
- tests/unittests/tools/stub_http_download.c
- tests/unittests/ui/stub_ui.c
Fixes https://github.com/profanity-im/profanity/issues/1794
Explanation
The problem is the download's identifier. Downloads are given an ID so they can be referenced later when their progress changes. Currently, the download's ID is the download's URL. When you download the same file twice, you have two downloads with the same ID. Download progress updates are shown on the first of both downloads with the same ID.
Solution
Change the download's ID from its URL to a random number. There is a new function in cmd_funcs.c named "_url_make_id()" that generates a random number for a download's ID. Several other functions are updated to cope with the new ID format.
> Fix duplicate download IDs when using "/url save"

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/common.c
- src/otr/otr.c
- src/pgp/gpg.c
- src/plugins/c_api.c
- src/tools/autocomplete.c
- src/tools/parser.c
- src/ui/confwin.c
- src/ui/console.c
- src/ui/privwin.c
- src/ui/window.c
- src/xmpp/contact.c
- src/xmpp/iq.c
- src/xmpp/muc.c
- src/xmpp/roster_list.c
glib 2.75.3 changes warning behaviour of `g_string_free()`.
See:
* https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3219
* https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3226
Use this opportunity to replace the use of GString with
`g_strdup_printf()` where possible.
Otherwise correctly take the return value of `g_string_free()`
which is nicer anyways
> Adapt to g_string_free glib 2.75.3 change

- src/event/server_events.c
- src/otr/otr.c
- src/ui/core.c
- src/xmpp/message.c
Fix of OTR in message.c: carbon in stanza breaks OTR and prevents it from starting and working properly
Fix of other encryption methods by calling correct function that would initiate them in case if someone writes.
PGP Bug Description
If someone writes using PGP and chat window was closed even if PGP was enabled before, PGP won't initiate, even though it should. The problem is in calling the wrong function to initiate window. It can make a user send a message which he expect to be encrypted in plain text, thus making a big security problem.
OTR Bug Description
If user tries to initiate OTR, it does not work. E.g. PSI+ will just print out the messages and other profanity client won't start the OTR session either. The problem is in the carbons inside of the message.
Minor formatting.
> Security fix of OTR, PGP and other

- .codespellrc
- src/log.c
- src/xmpp/vcard.c
- tests/unittests/test_parser.c
* Fix typos
* Add some words that cannot be fixed to codespell ignore words list.
* `make doublecheck` now is throwing no error
> Fix typos and add codespell configuration

- src/command/cmd_ac.c
After typing `/reconnect ` and pressing tab nothing appeared where in reality, it should have been autocompleted to `/reconnect now`
> Add autocomplete for the /reconnect command

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/config/preferences.c
- src/config/preferences.h
- src/ui/console.c
- src/ui/statusbar.c
The existing way how active tabs are displayed didn't allow showing more than 10 tabs. This patch adds a mode where the statusbar shows a comma-separated list of tabs which were active since the last time viewed.
This view is inspired by how `irssi` shows the active tabs, therefore it is also called `actlist`.
> add `/statusbar tabmode actlist`

- src/command/cmd_funcs.c
- src/omemo/omemo.c
- src/otr/otr.c
- src/profanity.c
- src/ui/chatwin.c
- src/ui/console.c
- src/ui/notifier.c
- src/xmpp/connection.c
- src/xmpp/iq.c
- src/xmpp/ox.c
As stated in
https://github.com/profanity-im/profanity/pull/1820#issuecomment-1498083383
profanity uses "..." (three dots) in a lot of places instead the proper
ellipsis char "…".
> User proper ellipsis char

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/config/account.c
- src/config/account.h
- src/config/accounts.c
- src/config/accounts.h
- src/ui/console.c
- src/xmpp/iq.c
- src/xmpp/stanza.c
- tests/unittests/config/stub_accounts.c
- tests/unittests/test_cmd_account.c
- tests/unittests/test_cmd_connect.c
- tests/unittests/test_cmd_join.c
- tests/unittests/test_cmd_otr.c
- tests/unittests/test_cmd_rooms.c
This privacy enhancing feature allows to change client name and version for each account that user have.
> Feature: Allow setting client identification name/version manually

- src/command/cmd_defs.c
- src/ui/statusbar.c
- src/ui/window.c
Fixes #1816 and more
See commit messages.
**Note:** on all of the screenshots setting `/statusbar self` set to `off` to preserve privacy of testing account.
> JID Display in Titlebar and Fix

- docs/profanity.1
The goal should be that users can make a more informed decision about which encryption they actually want to use.
We can also use this to document usage details of implementation quirks, if any.
> Add encryption section to man page

- src/command/cmd_funcs.c
> Fix `/plugins update`

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/xmpp/avatar.c
- src/xmpp/avatar.h
- src/xmpp/stanza.c
- src/xmpp/stanza.h
- tests/unittests/xmpp/stub_avatar.c
Add "/avatar disable" to comply with point "3.5 Publisher Disables Avatar Publishing" in XEP-0084.
**src/command/cmd_defs.c:2416**
Add "disable" argument. Reword the "/avatar" command description so it flows better.
**src/command/cmd_ac.c:1101**
Add "disable" to the "/avatar" autocomplete dictionary.
**src/command/cmd_funcs.c:9277**
Split "/avatar" commands into two groups with an if statement; those with a parameter and those without. "cons_bad_cmd_usage()" is in both groups, which is messy. "disable" has similar logic to "set", but it includes a failure message.
**src/xmpp/avatar.c:152**
"avatar_publishing_disable()" uses the same logic to publish metadata as in "avatar_set()".
**src/xmpp/avatar.c:238**
Add a message to inform users when they do not receive an avatar after using …
> Add ability to disable avatar publishing

- src/xmpp/iq.c
The strings have to be dup'ed, otherwise we'll free them twice.
Fixes #1855
Introduced by b6bb50ceb28250317351fd5115e3f187f0c56fba
> Fix double-free of values.

- configure.ac
This commit fixes few issues related to OMEMO autodetection:
1. Absence of libsignal-protocol-c doesn't turn OMEMO off, just prints a notice message. It should (a) set BUILD_OMEMO=false and (b) terminate with an error on --enable-omemo=yes.
2. Check for gcrypt continues even if libsignal-protocol-c fails. In this case, LIBS variable can be updated with unneeded -lgcrypt.
3. Similarly to item 2., if libsignal-protocol-c is present, but gcrypt isn't, variable LIBS is updated with unneeded library.
* step 1 install libgcrypt
* step 2 remove libsignal-protocol-c
* step 3 configure and build
> Fix OMEMO autodetection in autotools

- src/ui/core.c
Fixes #1874.
* Run profanity on wayland with screensaver  support compiled into profanity and monitor log file.
no
> Don't use xscreensaver on wayland.

- src/event/server_events.c
- src/ui/chatwin.c
and dont display them as legacy pgp encrypted messages. This was forgotten in 2c94ee5a8.
Fix https://github.com/profanity-im/profanity/issues/1875
no
> ox: correctly recognize ox encrypted carbons

- src/tools/http_download.c
- src/tools/http_upload.c
When we are not connected and run `/plugins install` we crash because we get the account struct to check for the (xmpp) tls setting. To apply that to the http (etc) connection to download the plugin from a server.
This got introduced in 3a86b8c29 to fix #1624.
There are several ways to handle this (some described in 1880) in this patch I took the route that it will use secure connection when we are nto connected and will only check the tls.trust account setting if we are connected.
Fix https://github.com/profanity-im/profanity/issues/1880
I ran valgrind when using my new feature
no
> Don't crash when using `/plugins install` disconnected

- src/ui/window_list.c
First I tried with g_uri_parse() and g_uri_to_string() but then I learned that GUri validation API is only for things that are part of a proper URL.
Let's cut the string at `>` since they are sometimes enclosed in `<>`.
Fix https://github.com/profanity-im/profanity/issues/1877
> Cut URLs before adding to automcomp at `>`

- src/omemo/omemo.c
We have to lazy load the keyfiles as they will maybe be written at one point and should be initialized by that time.
Reported by @H3rnand3zzz 
Fixup of ca2df180d81f1b30142e63cd7621a00eb9248913 resp. #1886
> Fix OMEMO keyfile loading

- src/database.c
Addressing unreliable message history reports where some messages were written in the file log but not in the DB. This issue was not consistently reproducible, but investigations revealed potential causes.
1. SQLite file access issues were ruled out, as they would trigger errors in the error log.
2. The problem could be due to the `WHERE` clause in the insert query, preventing message insertion.
To resolve this, I propose:
- Removing the `WHERE` clause from the insert query, allowing messages with duplicate IDs or stanza IDs to be inserted.
- Implementing a warning log for duplicate stanza-ids or archive-ids for further investigations.
I also am planning to offer an optional setting in the future to handle duplicate IDs or stanza IDs differently, to resolve potential duplicate messages …
> Improve logging of DB message insertion

- src/database.c
> Check sender for LMC messages

- src/command/cmd_defs.c
- src/command/cmd_funcs.c
See description
* Add an alias that can be used with params, e.g.
`/alias add m /msg`
use alias like a normal command (`/m friend Hello!`)
> Add params support for aliases

- src/ui/buffer.c
- src/ui/window.c
* Reach bottom and top of your conversations, you should see that (1) delay on page switching has been reduced and (2) that you can reach first and last message in the chat (though there already is unrelated bug, that's why, please, make sure that you can see first message without the update).
* Check whether MAM is working
* Use page up 10-20 times (to fill the buffer) and then page down until you see last messages. Then hold/click quickly page down. Lag should be much less noticeable than before changes were introduced.
> Improve history paging performance

- src/database.c
The column of the encryption type in the result is 4, not 3.
Fixup of 6375b2719fd16cbedf531ff197f6d82ffbcc873a
> Fix loading of encryption type

- src/command/cmd_funcs.c
- src/config/preferences.c
- src/config/preferences.h
- src/config/theme.c
* Set correction char to unicode character, e.g. `/correction char 🖋️`
* Use `/correct` command
> Add unicode support for correction char

- src/ui/chatwin.c
- src/ui/mucwin.c
- src/ui/window.c
- src/ui/window.h
See commit message.
* Use page up in the chat window until you see historical message. Encryption used should be displayed accordingly.
> Show encryption for historical messages

- src/database.c
- src/ui/chatwin.c
- src/ui/window.c
- src/xmpp/message.c
**Backup your DB before performing any testing.**
All tests should be done with the final version.
Even though it does not drop any tables, I want to be on the cautious side and avoid any potential data loss by current or future profanity developers.
It's not ready for release yet and just shows PoC. The point of the PR is to share the idea for further discussion and development. I am not even sure if it works properly or even works in some parts. In 1 day I plan to tidy it up and make it generally better.
Read commit message for further details. Discussion links are going to be attached here and in commit message later.
The initial problem is that when we receive messages from old client, they can have duplicate IDs and currently we don't even write them to DB, but it goes much further …
> Change DB structure

- src/database.c
#1915 unsuccessfully tried to fix strdup(message) when message is NULL, since it lead to a chain reaction that can be ungracefully fixed like this: https://github.com/profanity-im/profanity/commit/c1c2113a3a2c66db160757d7169ee18610b3c29a or instead we could use strdup("") to substitute an empty message.
> Improve handling of NULL pointers fetched from DB

- src/tools/http_download.c
Use `/plugins install <redirect_link>`, e.g. `/plugins install https://github.com/profanity-im/profanity-plugins/raw/master/stable/syscmd.py`
To test emptiness check, I would suggest finding some empty file that ends up with `.c` or `.py` for the purpose of testing.
Fix #1901
> Allow redirects for  `/plugins install` and add emptiness check for downloaded files

- tests/unittests/test_cmd_otr.c
This pull request is a minor code formatting adjustment, removing unnecessary space. No further details are needed.
> Format `test_cmd_otr.c`

- src/database.c
See commit message for details.
Fix https://github.com/profanity-im/profanity/issues/1925
> Do not check for unique `stanza-id` for MAM messages 

- docs/profanity.1
- src/ui/inputwin.c
See commit message.
Write a message and use alt+enter during writing to put a new character symbol there. Plain "Enter" for sending message/command should work as well as before.
Well, you see, shift+enter and ctrl+enter aren't that bindable, as you can see by using `showkey --ascii` command. Though shift/ctrl variants might be more preferable since they are used in some popular applications, we just can't bind on them using GNU Readline, while alt+enter does the work as well. 
I will be glad if someone can improve the solution to take keybinding from preference and allow custom settings for ctrl+enter, shift+enter etc. Though even current solution will suffice in terms of functionality and you can get used to it quite quickly.
> Handle alt+enter as newline char

- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/command/cmd_funcs.h
> Introduce `/redraw` command

- src/config/conflists.c
> Fix mem leak in `conf_string_list_add`

- src/plugins/plugins.c
- src/plugins/plugins.h
- src/ui/chatwin.c
- /plugins install https://raw.githubusercontent.com/profanity-im/profanity-plugins/master/stable/emoticons.py
- Send a message with emoticons. E.g. `Hello, how are you today? :)`
- Message is being **replaced**
Fix #1917
> Fix `prof_pre_chat_message_display` does not replace sent messages + minor refactoring

- src/command/cmd_ac.c
- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/ui/statusbar.c
Display current pages dynamically so users can navigate easily in-depth.
* Use the following commands (for easier testing, you can add them to `scripts/msg` folder and `/account set YOUR_ACCOUNT startscript msg` (BEWARE: can cause occasional strophe-related crash, use 10-15 windows for safety and make `/statusbar maxtabs 5` to see the effect better)
```
/msg 1
/msg 3
/msg 4
/msg 5
/msg 6
/msg 7
/msg 8
/msg 9
/msg 10
/msg 11
/msg 12
/msg 13
/msg 14
/msg 15
/msg 16
/msg 17
/msg 18
/msg 19
```
* navigate through pages easily
* use `/statusbar hide name`, `/statusbar show name`, `/statusbar hide number` to test all the possible mods.
Potentially fixes #1764.
Fixes #1283
> Add new mode for statusbar tab behaviour

- src/plugins/python_plugins.c
A bit hard to reproduce. You need to add a plugin with the following code (or any other plugin with `prof_pre_chat_message_display` present, such as emoticons.py):
```python
def prof_pre_chat_message_display(barejid, resource, message):
return message
```
and then receive/send message with incorrectly encoded character, it can be any invalid UTF8 symbol. You'll see error in console, errors don't represent actual errors in plugins, but rather Profanity's shortcoming, though it make appear so that the problem is in plugin.
Actual proper handling would likely be using `y` instead of `s` format (see [reference](https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue))
> s ([str](https://docs.python.org/3/library/stdtypes.html#str) or None) [const char *]
>    Convert a null-terminated C …
> Improve string convertion error handling

- src/ui/window.h
> Fix underscrolling problem

- docs/profanity.1
- src/command/cmd_funcs.c
- src/ui/inputwin.c
- src/ui/window.c
- src/ui/window.h
Added mouse scroll support with shift+scroll using readline.
Points before release:
Known Issues: Sometimes it gets incredibly laggy (probably have something to do with profanity core)
> Smooth scrolling support (+mouse wheel scrolling in some terminals)

- src/ui/win_types.h
- src/ui/window.c
See commit message, it's descriptive.
No memory stuff -> no need for valgrind.
> Fix scrolling state at windows edge

- src/event/server_events.c
- src/xmpp/iq.c
- src/xmpp/iq.h
- tests/unittests/xmpp/stub_xmpp.c
Feature discovery was marked as finished once we received a reply to the initial request. The discovery mechanism allows to delegate the real feature discovery to another service running on different domain and those requests are created dynamically.
This was another instance causing the warning message described in #1940
Fixes #1940 (once more)
* have an account on a server that delegates feature discovery like hot-chilli
* send a 1-on-1 message to that account while being offline
* connect to that account
Before the patch you would receive the warning when connecting to the server and the server delivers the 1-on-1 message before feature discovery was finished.
> Fix when feature discovery is finished

- src/database.c
- src/ui/buffer.c
- src/ui/buffer.h
- src/ui/window.c
Current state:
- Fixes "overscrolling"
- Lag reduction (only necessary lines are being drawn)
Currently it's full of debugging lines with some issues which are to be fixed before release:
Fix https://github.com/profanity-im/profanity/issues/1934
> Fix scrolling

- Makefile.am
- src/profanity.c
- src/profanity.h
- src/ui/inputwin.c
- src/ui/inputwin.h
- tests/unittests/ui/stub_inputwin.c
- tests/unittests/ui/stub_inputwin.h
Potential improvements:
---
Current version significantly improves performance, especially noticeable on alt+scroll.
> Use Gmainloop as a main loop to increase performance

- src/ui/inputwin.c
* Use `/editor` and write some stuff, after this save and close, input should be updated.
> Remove unnecessary input win redisplay

- src/command/cmd_funcs.c
- src/tools/aesgcm_download.c
Partial fix for https://github.com/profanity-im/profanity/issues/1939  
> When doing the same in an unencrypted (no e2ee) chat there is no Downloading… message at all but the file is downloaded.  
Download a file twice with `/url save`, the second download will not print download progress to the window.  
The cause is `HTTPDownload`'s `silent` variable is not initialized; so, `silent` points to a second-hand stack memory address with old data. `silent` references data, so the `if` statement will fail in **src/tools/http_download.c:206** and download progress will not print to the window.  
The fix is to initialize `silent` in both encrypted and unencrypted file download scenarios.  
Valgrind: Yes  
- `/url save` without OMEMO  
**SUCCESS**: Try three times with the same URL and download …
> Fix unable to download item twice

- src/ui/window.c
See commit message
* open a window with a chat with considerably sized message log (400 messages at least)
* scroll up at least 300 messages
* Alt+scroll down (mouse wheel down/arrow down)
> Fix underscrolling issue for alternative scrolling

- .github/workflows/main.yml
We get some build fails there and I don't see what's the problem on a first glance. Noone else stepped up neither.
> ci: disable macOS for now

- src/command/cmd_funcs.c
When users receive a message and a subscription request from a new contact, and they use `/blocked report-abse JID` or `/blocked report-spam JID` they most likely want the subscription request to vanish as well.
According to mdosch Conversations is behaving like this too.
Fix: https://github.com/profanity-im/profanity/issues/1970
> Remove subscription when reporting spam/abuse

- src/command/cmd_funcs.c
- src/event/client_events.c
- src/event/server_events.c
- src/omemo/omemo.c
- src/otr/otr.c
- src/plugins/plugins.c
- src/ui/chatwin.c
- src/ui/console.c
- src/xmpp/bookmark.c
- src/xmpp/jid.c
- src/xmpp/message.c
- src/xmpp/presence.c
- src/xmpp/session.c
- src/xmpp/xmpp.h
- tests/unittests/xmpp/stub_xmpp.c
Some minor improvements of the code and fix a crash when creating a new OMEMO session (as in "setup OMEMO for an account").
> Minor improvements

- src/command/cmd_funcs.c
When a user added an account, set it as autoconnect and then removed that account. It still was set as the autoconnect account.
```
/account add test
/autoconnect set test
/account remove test
/save
/quit
Start profanity
```
Fix https://github.com/profanity-im/profanity/issues/1976
> Reset autoconnect account when the account gets removed

- src/ui/statusbar.c
This lets users use the actlist and decide if they want to see name or numbers.
Fix https://github.com/profanity-im/profanity/issues/1974
> Make statusbar actlist respect the /statusbar show setting

- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/config/files.c
- src/config/files.h
`/url save $someurl` will now download to
`~/.local/share/profanity/downloads/from_jid/date/filename` instead of `~/.local/share/profanity/downloads`.
Like this the downloaded files should be better ordered.
This will only happen for MUC and 1:1 chat windows. Private windows might have only a nick or jid. Lets not distinguish between those two ways. And since the nick option is unreliable to be the same person lets just put them in the general downloads folder. As is done with downloads from all other windows as well.
I also had the idea to make this configurable but this suits my needs and time limits right now.
> Change default download location

- tests/unittests/config/stub_accounts.c
- tests/unittests/tools/stub_http_upload.c
- tests/unittests/xmpp/stub_avatar.c
Fix https://github.com/profanity-im/profanity/issues/1992
> Fix outdated types in tests

- src/xmpp/iq.c
- src/xmpp/ox.c
There were two cases of plenking (a space between a word and the punctuation
marks) in front of `…`.
Should not be necessary as only two strings were changed (space removed).
* If it builds it should be fine.
> Remove plenking

- .github/workflows/main.yml
- Dockerfile.arch
For some reason GH didn't update https://github.com/profanity-im/profanity/issues/2004 when I tried to push to that branch. So here is a new PR.
> Enable Arch CI

- src/chatlog.c
- src/command/cmd_funcs.c
- src/event/server_events.c
- src/plugins/api.c
- src/plugins/python_api.c
- src/ui/core.c
- src/ui/mucwin.c
- src/xmpp/muc.c
- src/xmpp/muc.h
- src/xmpp/presence.c
- src/xmpp/stanza.c
In the documentation of the `muc_nick` function we can read:
> The nickname is owned by the chat room and should not be modified or freed
We should reflect that in the return type and `strdup` the value for the plugin API.
Fixes: https://github.com/profanity-im/profanity/issues/2013
> Make `muc_nick` return a `const char* const`

- src/plugins/plugins.c
- src/plugins/plugins.h
- src/ui/chatwin.c
- src/ui/ui.h
- src/ui/window.c
- src/ui/window.h
- tests/unittests/ui/stub_ui.c
In order to keep the plugins API stable, we have to partially revert 16ed7cc18720820e22fba881fc50df7ead42ffb2.
> Revert plugins api breakage

- src/command/cmd_funcs.c
- src/omemo/crypto.c
- src/omemo/omemo.c
- src/tools/aesgcm_download.c
- src/tools/http_download.c
- src/tools/http_download.h
- src/tools/http_upload.c
- src/tools/plugin_download.c
> Debug & fix #1994

- src/command/cmd_defs.c
- src/command/cmd_funcs.c
- src/config/preferences.c
- src/config/preferences.h
- src/ui/window.c
- src/ui/window_list.c
- src/xmpp/roster.c
> Some improvements

- src/command/cmd_defs.c
* Run `/help info`
* See Asgard is called Asgard and not Aasgard :D
> Fix typo in examples.

- tests/unittests/config/stub_accounts.c
- tests/unittests/log/stub_log.c
- tests/unittests/test_autocomplete.c
- tests/unittests/test_chat_session.c
- tests/unittests/test_common.c
- tests/unittests/test_jid.c
- tests/unittests/test_parser.c
- tests/unittests/test_preferences.c
- tests/unittests/test_roster_list.c
on openSUSE Tumbleweed, when running tests and using gcc15:
````
[   13s] In file included from tests/unittests/test_preferences.c:4:
[   13s] tests/unittests/test_preferences.c: In function ‘statuses_console_defaults_to_all’:
[   13s] tests/unittests/test_preferences.c:16:5: error: ‘uintptr_t’ undeclared (first use in this function)
[   13s]    16 |     assert_non_null(setting);
[   13s]       |     ^~~~~~~~~~~~~~~
[   13s] tests/unittests/test_preferences.c:10:1: note: ‘uintptr_t’ is defined in header ‘<stdint.h>’; this is probably fixable by adding ‘#include <stdint.h>’
[   13s]     9 | #include "config/preferences.h"
[   13s]   +++ |+#include <stdint.h>
[   13s]    10 |
````
Investigation shows that this is exclusive to gcc15, and `tests/`. This PR fixes `error: ‘uintptr_t’ …
> Fix tests with gcc15 (uintptr_t)

- src/common.c
Fixes #1911
Alternative to #2056
> If config keyfile does not exist, create it.

- src/tools/bookmark_ignore.h
- src/ui/ui.h
Running make (macOS, Clang 16.0.0) results in errors complaining about passing arguments without function prototypes.
Specifically:
- bookmark_ignore_on_connect()
- cons_show_qrcode()
Adding parameters to prototypes results in successful build.
> Add types to function prototypes
