profanity-im/profanity

install-all.sh
For issue #546.
Fix only for Debian.
=> Udpate installer.sh to include uuid-dev

src/pgp/gpg.c
This patch should fix problem that is described in #567, but I can't check it.
=> Added include config.h to pgp/gpg.c

src/log.c, src/log.h, src/profanity.c, tests/unittests/log/stub_log.c
This patch fixes #562. So, ignore #565.
=> Introduced stderr log handler

src/ui/inputwin.c
=> Ignore EINTR in inp_readline()

install-all.sh
I had problems cloning and https worked like a charm, maybe this helps others to install as well.
=> updated intaller to clone libmsode over https

tests/unittests/helpers.c
Run fclose after fopen in unittests.
=> Fix resource leak

src/event/server_events.c
Fixes build with `configure --disable-pgp`
=> Don't compile pgp code with --disable-pgp

src/command/command.c, src/command/commands.c, src/command/commands.h, src/config/preferences.c, src/config/preferences.h, src/profanity.c, src/ui/console.c, src/ui/ui.h
Allow to enable/disable the tray icon.
=> Make tray icon configurable using /tray cmd

src/event/client_events.c
=> Add missed argument

src/xmpp/iq.c
fixes #859
This patch has not been tested.
=> Disable autoping if server doesn't support it

profanity.spec
=> Set version in spec file to current

CHANGELOG
Seems important enough and I had to spelunk through the commit history to figure out which version this was for, so I figured I'd send a patch :thumbsup:
=> Note CVE-2017-5592 in the CHANGELOG

src/ui/core.c
This fixes issue #1044 - I also found the same pattern in a few other places in src/ui/core.c.
=> Fix use after free bug

src/command/cmd_funcs.c
=> Avoid use after free on default account 

.travis.yml, Dockerfile
=> Move travis from Ubuntu to docker+openSUSE

src/command/cmd_funcs.c
=> Alert about long OMEMO cryptographic generation

src/command/cmd_funcs.c, src/xmpp/muc.c, src/xmpp/muc.h
Store MUC anonymous type in mucwin for that purpose.
Fixes #1065
=> Ensure MUC is Non-Anonymous before starting OMEMO

Makefile.am
Fixes https://github.com/boothj5/profanity/issues/973
=> Add library versioning to libprofanity

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/config/preferences.c, src/config/preferences.h, src/config/theme.c, src/ui/console.c, src/ui/occupantswin.c, theme_template
Regards https://github.com/boothj5/profanity/issues/690
@kaffekanne asked for this.
=> Add /occupants indent option

src/ui/console.c
Small fix of indention visible when usig `/prefs`. Also first PR! \o/
=> Fix indentation time confing

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/config/preferences.c, src/config/preferences.h, src/config/theme.c, src/ui/console.c, src/ui/occupantswin.c, src/ui/ui.h, tests/unittests/ui/stub_ui.c, theme_template
Regards https://github.com/boothj5/profanity/issues/690
=> Occupants header char

LICENSE.txt, docs/profanity.1, src/main.c
ok, this PR was generated using `hub` as wrapper for `git`. So if i missed something (except this description), tell me.
I am not completely sure about the first line in profanitys manpage `profanity.1`, `LICENSE.txt` and `main.c` probably went under your radar, when you did the last copyright fixes.
=> Update copyright years

src/config/theme.c
There is a typo here. So this actually never worked ;-)
=> Fix statusbar number in theme

src/xmpp/omemo.c
Fixes https://github.com/boothj5/profanity/issues/1079
=> OMEMO: Check if ID is present before using it

src/event/server_events.c
Remove the windows, clear tls certs, clean omemo.
Regards https://github.com/profanity-im/profanity/issues/1089
=> Reset things on connection loss

Makefile.am, src/event/client_events.c, src/event/common.c, src/event/common.h, src/event/server_events.c
Duplicate code in client_events.c and server_events.c. Let's have
events/common.c and a function containing that code.
=> Create seperate function for disconnect cleanup

src/omemo/omemo.c
=> Correctly handle malformed OMEMO messages

src/xmpp/connection.c
When connection is lost, profanity tries to disconnect what leads
to an infinite loop. The loop occurs, because connection_disconnet()
runs xmpp_run_once() separately and waits for XMPP_CONN_DISCONNECT
event. But it doesn't happen, because the connection object is
disconnected.
As solution, don't disconnect after XMPP_CONN_DISCONNECT is received.
Also, don't free libstrophe objects while the event loops executes,
because the event loop continues using objects after callbacks quit.
=> xmpp/connection: fix #1103

src/xmpp/session.c
If connection loss occurs, it calls session_disconnect() eventually.
This function clears saved account data which is required for
reconnection. Therefore, when reconnect timer expires, we get errors:
```
02/06/2019 04:53:42: stderr: ERR: (profanity:17115): GLib-CRITICAL **: 04:53:42.305: g_key_file_has_group: assertion 'group_name != NULL' failed
02/06/2019 04:53:43: prof: ERR: Unable to reconnect, account no longer exists: (null)
```
To solve it, don't clear the saved data in session_disconnect(). It will
be cleared properly on connection loss if reconnect timer is not
configured. But won't be cleared with /disconnect command.
So, after /disconnect the data will live in memory until the next
/connect.
Also, remove some copy-paste in connection loss path.
=> Don't clear saved account data in session_disconnect()

src/ui/statusbar.c, src/xmpp/roster_list.c, src/xmpp/roster_list.h
This should fix https://github.com/profanity-im/profanity/issues/1083. Please somebody help testing it.
Some UI improvements will follow separately for https://github.com/profanity-im/profanity/issues/704.
=> Fix SIGABRT on lost connection

src/config/theme.c, theme_template, themes/bios, themes/boothj5, themes/boothj5_laptop, themes/boothj5_slack
@paulfariello could you review? :)
=> Add omemo.char to themes

src/log.c
Fix https://github.com/profanity-im/profanity/issues/519
=> Iterate logfiles until 100 are reached

src/event/server_events.c
Should fix https://github.com/profanity-im/profanity/issues/1120
@ccxcz  can you test this please?
=> Rejoin all MUCs on reconnect

src/omemo/omemo.c, src/ui/statusbar.c, src/xmpp/bookmark.c, src/xmpp/iq.c, src/xmpp/message.c, src/xmpp/message.h, src/xmpp/session.c, src/xmpp/xmpp.h, tests/unittests/test_cmd_otr.c, tests/unittests/test_cmd_presence.c, tests/unittests/test_preferences.c
Draft PR for now. More fixes will follow.
=> Fix memory leaks

src/xmpp/roster.c
Also regarding destructor.
Fix https://github.com/profanity-im/profanity/issues/1159
=> Fix segfault in group add/remove command

Makefile.am, src/config/color.c, src/config/color.h, src/config/theme.c
Themes can now use color names from the xterm color name list [1].
1: https://jonasjacek.github.io/colors/
=> Add 256 colors support

src/log.c
Glib can print error messages to stderr and blocking write freezes
Profanity if the buffer is full. Move stderr to nonblocking mode
in hope that glib will skip printing on EWOULDBLOCK error. In this
case we lose some error messages, but Profanity continues working.
Fixes #1186
=> log: set nonblocking mode for stderr

Makefile.am, configure.ac, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/command/cmd_funcs.h, src/tools/clipboard.c, src/tools/clipboard.h
For https://github.com/profanity-im/profanity/issues/156
=> Paste command

src/omemo/crypto.c, src/omemo/crypto.h, src/omemo/omemo.c
=> Add support for OMEMO 12 byte IV

.travis.yml, Dockerfile.tumbleweed, ci-build.sh
Force a Docker upgrade for all Linux runners.
Fixes: #1294
=> Use latest Docker in CI

ci-build.sh
=> Fallback for nproc for systems without GNU coreutils

src/ui/inputwin.c
When I shut my system down and profanity was killed, I got messages from valgrind that `g_utf8_get_char()` and `g_unichar_isprint()` use uninitialized memory. The scenario when memory can be uninitialized is that `bytes` is not set by `wcrtomb()`. I assume that the function returns an error which is `(size_t)-1`. Handle this situation.
Also, don't pass NULL to `wcrtomb()`, because we can call different external code in pthreads and there is no guarantee that the external libraries don't call this function.
=> Make _inp_edited() more robust

src/ui/window.c, src/ui/window_list.c
Fix mistake in a condition. Also add sanity check to `win_refresh_with_subwin()`.
=> Fix condition in wins_show_subwin()

src/log.c, src/main.c
Changed default logging from INFO to WARN.
Issue: #1353
=> Rework logging

.travis.yml, Dockerfile.ubuntu
Feel free to close if you do not want Ubuntu in the pipeline.
=> Ubuntu Latest (20.04 currently) in CI

src/tools/parser.c
`parse_args()` and `parse_args_with_freetext()` shared a lot of common
code.
Let's have a helper function `_parse_args_helper()` for that. The
`with_freetext` parameter will make it behave like
`parse_args_with_freetext()`.
In preparation for https://github.com/profanity-im/profanity/issues/1404
=> parser.c: Use helper function to reduce duplicate code

src/database.c, src/xmpp/message.c, src/xmpp/stanza.h, src/xmpp/xmpp.h
Regards https://github.com/profanity-im/profanity/issues/660
=> MAM: Only add each message once to database

src/xmpp/message.c
jid_create() for attribute "to" was called twice and the 1st object was lost.
=> Fix memory leak in _handle_chat()

themes/gruvbox
Update background color, closer to the vim theme.
=> Update gruvbox theme (background color)

src/command/cmd_funcs.c, src/common.c, src/ui/chatwin.c
=> Cast chat/muc window to correct type and refactor cmd_sendfile

src/command/cmd_defs.c, src/command/cmd_funcs.c, src/command/cmd_funcs.h, src/ui/core.c, src/ui/ui.h, src/xmpp/connection.c, src/xmpp/iq.c, src/xmpp/stanza.c, src/xmpp/stanza.h, src/xmpp/xmpp.h, tests/unittests/ui/stub_ui.c, tests/unittests/xmpp/stub_xmpp.c
I used this to learn how to read XEPs and how stanzas work.
I followed https://xmpp.org/extensions/xep-0077.html#usecases-changepw
Open questions:
- How to name command/functions
- Should we confirm the password (ask user to enter it twice)
- Check connection encryption?
=> Add command to change password of logged in user

src/tools/autocomplete.c
@StefanKropp, @wstrm, @xenrox, @mwuttke97 could one of you review?
=> Cleanup autocomplete

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/xmpp/message.c, src/xmpp/stanza.c, src/xmpp/stanza.h, src/xmpp/xmpp.h, tests/unittests/xmpp/stub_xmpp.c
closes https://github.com/profanity-im/profanity/issues/1211
=> MUC: Add voice request

src/command/cmd_funcs.c, src/config/preferences.c
https://github.com/profanity-im/profanity/pull/1485#discussion_r641971784
=> external editor: don't use absolute paths and allow path search

src/ui/mucwin.c
Fix https://github.com/profanity-im/profanity/issues/1231
=> Fix wrong message display when mention is triggered

src/omemo/omemo.c
In profanity are two handlers for device list:
* _handle_own_device_list
* _handle_device_list_start_session
I seems both handler will start a session via
omemo_start_device_session_handle_bundle
_handle_own_device_list will also make sure, that the own device is withing the
omemo device list. If we add the _handle_device_list_start_session into the
hashmap, we are not going the republish ourself, in case we clean-up the device
list from another client.
This will maybe fix #1552
99 Little Bugs in my Code.
Take one down.
Patch it around.
113 Bugs in my Code
=> OMEMO: Separate handling of device list

src/xmpp/message.c, src/xmpp/stanza.h
Display a notice in the console when someone tries to call us.
Implement https://github.com/profanity-im/profanity/issues/1525
=> XEP-0353: Display a notice when receiving a call

src/database.c
Some more parameters might contain quotes, so just escape all of them with %q by using sqlite3_mprintf.
For more information about %q see https://sqlite.org/printf.html
=> Escape all parameters in SQL statements

src/command/cmd_defs.c, src/ui/console.c, src/ui/ui.h, src/xmpp/iq.c, src/xmpp/stanza.c, src/xmpp/stanza.h
Implement https://github.com/profanity-im/profanity/issues/1524
=> Add support for XEP-0157 server contact information discovery

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/xmpp/blocking.c, src/xmpp/iq.c, src/xmpp/stanza.h, src/xmpp/xmpp.h, tests/unittests/xmpp/stub_xmpp.c
Report and block:
`/blocked add someone@domain.org report-abuse This is not nice`
`/blocked add someone@domain.org report-spam This is not nice`
Regular block:
`/blocked add someone@domain.org`
Implement https://github.com/profanity-im/profanity/issues/1434
=> Add XEP-0377: Spam Reporting

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/pgp/gpg.c, src/xmpp/message.c, src/xmpp/ox.c
* autocomplete for /ox discover
* fixed help description
* Implemented /ox char command
* Validated KeyID length
=> Bugfixes for OX implementation

src/command/cmd_funcs.c
=> Initialize jid

src/command/cmd_ac.c
Just a copy-past of autocomplete trust implementation.
=> OMEMO autocomplete untrust

apidocs/python/src/prof.py
Probably a refactoring that didn't go well.
=> Fix examples in python API doc

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/command/cmd_funcs.h, src/xmpp/iq.c, src/xmpp/message.c, src/xmpp/session.c, src/xmpp/stanza.h, src/xmpp/xmpp.h, tests/unittests/xmpp/stub_xmpp.c
Implementation of XEP 0107 - User Mood
=> XEP 0107 - User Mood

src/xmpp/connection.c
This adds the missing IPv6 handling to `_split_url()`
=> Fix `_split_url()`

src/xmpp/connection.c
unfortunately this https://github.com/profanity-im/profanity/pull/1631#issuecomment-1026982455 became true pretty quickly ...
=> Fix `_split_url()` once more

configure.ac, src/plugins/python_api.c, src/plugins/python_plugins.c
=> Fix python executed during configure

src/command/cmd_defs.c, src/common.c, src/common.h, src/config/files.c, src/config/files.h, src/database.c, src/log.c, src/omemo/omemo.c, src/otr/otr.c, src/pgp/gpg.c, src/tools/editor.c, src/ui/inputwin.c, src/xmpp/connection.c, tests/unittests/helpers.c
This PR started by looking into the editor implementation and finding some erroneous behavior https://github.com/profanity-im/profanity/pull/1645#issuecomment-1057127993
Now you can have a look at the commit history what was all done ... :joy: 
Most important things:
* fixing the issue described in the linked comment above
* changed editor spawning to `Alt+c` as `Alt+e` is already bound to something else
* a bunch of refactorings and simplifications (I hope I didn't break anything :grimacing:)
=> Refactor editor & some other parts

.github/workflows/main.yml, .gitignore, Makefile.am, src/command/cmd_funcs.c, src/config/preferences.c, src/ui/window.c, src/xmpp/connection.c
Please check the commit messages for details.
=> More cleanup

docs/profanity.1
=> Man page improvements

docs/profanity.1
=> Document custom input configuration in man page

src/command/cmd_defs.c, src/command/cmd_funcs.c, src/ui/window.c, tests/unittests/test_cmd_account.c
see commit messages for details
=> Even moar cleanup

src/ui/inputwin.c
=> Make all existing input functions bindable from config

src/ui/inputwin.c
Factor out common code for Tab and Shift-Tab in a separate function.
No functional change.
=> Tab completion code simplification

src/ui/window.c
=> Use correct colour for their nick when showing history

src/config/theme.c
=> Allow bold for default colours

docs/profanity.1
Add mentions of less-known but quite useful bindindings to the man
page.
=> Mention C-x C-r (reload inputrc) in the man page

src/config/preferences.h, src/log.c
Saner defaults and one cleanup.
=> Log file improvements

src/command/cmd_ac.c
=> Fix autocomplete for `/ox discover`.

profanity.doap
=> DOAP: Use correct namespace for xmlns:schema

Dockerfile.arch, Dockerfile.debian, Dockerfile.fedora, Dockerfile.tumbleweed, Dockerfile.ubuntu, ci-build.sh, configure.ac, src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/command/cmd_funcs.h, src/ui/console.c, src/ui/ui.h, tests/unittests/ui/stub_ui.c
https://github.com/profanity-im/profanity/issues/1320
=> Show OMEMO QR Code

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/config/preferences.c, src/config/preferences.h, src/ui/console.c, src/ui/ui.h, src/xmpp/session.c, tests/unittests/ui/stub_ui.c
Make display of user mood optional.
And display its settings.
=> Make display of user mood optional

src/config/preferences.c, src/ui/console.c
Explaining how to register/connect/set up an account.
=> Display a help message upon first start of Profanity

src/common.c
Related to https://github.com/profanity-im/profanity/issues/1738
=> Check for error before trying to append it

src/xmpp/connection.c
* save SM state and send-queue entries on disconnect
* restore SM state and send-queue entries on reconnect
fixes #698
=> integrate XEP-0198 Stream-Management

src/xmpp/connection.c
=> fixup 11f52ad5474c7adb7f11df5b0c318597e4150312

src/log.c, src/profanity.c, src/tools/http_download.c
Check commit messages for details
=> Minor improvements

src/ui/chatwin.c, src/ui/mucwin.c, src/ui/window.c
=> Improve some UI functions

src/command/cmd_ac.c, src/tools/autocomplete.c, src/ui/confwin.c
Check commit messages for details
=> Improvements and bugfixes

src/xmpp/iq.c
Fix release of os and os_txt stanzas.
In some environments it breaks the build.
=> Hotfix stanza release

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, tests/functionaltests/functionaltests.c, tests/functionaltests/test_roster.c, tests/functionaltests/test_roster.h, tests/unittests/test_cmd_roster.c, tests/unittests/test_cmd_roster.h, tests/unittests/unittests.c
=> Add nickname support for `/roster remove`

src/ui/inputwin.c
=> Don't add the same command twice to history

src/command/cmd_funcs.c, src/event/server_events.c
=> Fix crash, add consistency to logging

src/ui/inputwin.c, src/xmpp/stanza.c
Got introduced with 5d3c8ce7c.
=> Fix two recently introduced memleaks

src/chatlog.c, src/command/cmd_ac.c, src/command/cmd_funcs.c, src/common.c, src/config/files.c, src/config/preferences.c, src/config/theme.c, src/config/tlscerts.c, src/event/server_events.c, src/main.c, src/omemo/omemo.c, src/omemo/store.c, src/plugins/python_plugins.c, src/profanity.c, src/tools/autocomplete.c, src/tools/http_upload.c, src/ui/confwin.c, src/ui/mucwin.c, src/xmpp/capabilities.c, src/xmpp/jid.c, src/xmpp/message.c, src/xmpp/omemo.c, src/xmpp/stanza.c, tests/unittests/test_cmd_join.c, tests/unittests/test_cmd_otr.c, tests/unittests/test_common.c
See commit messages. Partially fixes/cleans up #1819
=> Cleanup: gchar as gchar instead of char

src/command/cmd_ac.c, src/command/cmd_defs.c, src/command/cmd_funcs.c, src/common.c, src/common.h, src/main.c, src/profanity.c, src/ui/console.c, src/ui/core.c, src/ui/ui.h, src/xmpp/capabilities.c, src/xmpp/iq.c, src/xmpp/stanza.c, tests/unittests/ui/stub_ui.c
Fix https://github.com/profanity-im/profanity/issues/1836
=> Move related commands as subcommands into /privacy

.github/workflows/main.yml
This reverts commit a815e251b650ab5214666575db84b217969dc1cb.
=> ci: reenable macos

src/config/preferences.c, src/config/preferences.h, src/log.c, src/log.h, src/ui/buffer.h, src/ui/chatwin.c, src/ui/confwin.c, src/ui/console.c, src/ui/mucwin.c, src/ui/occupantswin.c, src/ui/privwin.c, src/ui/rosterwin.c, src/ui/titlebar.c, src/ui/ui.h, src/ui/vcardwin.c, src/ui/window.c, src/ui/window_list.c, src/ui/xmlwin.c
Split up #1884 into multipe PR's, this one only contains the trivial fixes.
=> Fix some stuff

src/common.c, src/ui/console.c, src/ui/ui.h, src/ui/window.c
Please check commit messages for details.
=> Refactor some internals

src/common.c, src/common.h, src/config/accounts.c, src/config/files.c, src/config/preferences.c, src/config/tlscerts.c, src/omemo/omemo.c, src/pgp/gpg.c, src/plugins/settings.c, src/plugins/themes.c, src/tools/bookmark_ignore.c, src/xmpp/capabilities.c, src/xmpp/connection.c
Split up #1884 into multipe PR's, this one contains the unification of the keyfile loading.
=> Unify keyfile loading

src/command/cmd_funcs.c, src/event/client_events.c, src/ui/window.c
Commit description provides enough data.
Fix https://github.com/profanity-im/profanity/issues/1894
=> Fix 2 crashes on reconnection

docs/profanity.1
This PR got opened by @jubalh for Stefan who sent this patch in the profanity MUC.
=> Add section `Using profanity` to profanity.1

.github/workflows/main.yml, src/command/cmd_funcs.c, src/database.c, src/omemo/omemo.c, src/ui/chatwin.c, src/ui/console.c, src/ui/mucwin.c, src/ui/window.c, src/ui/window.h, src/xmpp/avatar.c, src/xmpp/message.c, src/xmpp/vcard.c, src/xmpp/xmpp.h
=> Ensure instances of auto types are initialized

src/database.c
Follow-up of 89dc7a46f13b452a1dba7fa8237ad5efbf8f3a2d resp. #1902
=> Handle potential NULL pointers in database

src/config/conflists.c
=> Fix double free crash

src/config/conflists.c
Try to `/omemo end`, `/omemo start` and check how it affects `accounts` config file. You can try load, unload plugins as well.
=> Minor `config/conflists.c` refactoring

src/ui/inputwin.c
See commit message.
Separated from #1824 to make PRs cleaner.
=> Minor `inputwin.c` refactoring/cleanup

src/command/cmd_funcs.c
See commit message for details.
=> Fix unintended exits on some commands

src/command/cmd_funcs.c
We do this for regular chatwins already.
=> Check whether we are already in an omemo session for MUCs as well

src/database.c
Fixes: https://github.com/profanity-im/profanity/issues/201
=> Load resources from chat history db

.github/workflows/main.yml, .gitignore, src/command/cmd_funcs.c, src/common.c, src/common.h, src/tools/aesgcm_download.c, src/tools/plugin_download.c
=> Memory fixes

src/command/cmd_funcs.c, src/tools/aesgcm_download.c, src/ui/console.c, src/ui/window_list.c, src/xmpp/jid.c, src/xmpp/jid.h, src/xmpp/presence.c, src/xmpp/roster_list.c, tests/unittests/test_jid.c
=> Some improvements
